function varargout = straincompensation(varargin)
%This m-file was written in MATLAB R2013a, and is part of the
%project: straincompensation
%This file, along with all documentation can be found at:
%https://github.com/spolly/straincompensation
%
%Copyright (C) 2014 Stephen J. Polly, RIT
%
%This program is free software: you can redistribute it and/or modify
%it under the terms of the GNU General Public License as published by
%the Free Software Foundation, either version 3 of the License, or
%(at your option) any later version.
%
%This program is distributed in the hope that it will be useful,
%but WITHOUT ANY WARRANTY; without even the implied warranty of
%MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%GNU General Public License for more details.
%
%You should have received a copy of the GNU General Public License
%along with this program.  If not, see <http://www.gnu.org/licenses/>.
%=========================================================================
%Author's Note:
%The majority of this code was generated automatically. The .fig file was 
%created in the GUIDE package in MATLAB, which was also used to exprt this
%code.
%
%The important bits of functionality can be found in lines 782-993 in the 
%functions 'calculate_Callback', 'getMaterial', and 'calcMaterial'.
%=========================================================================

% STRAINCOMPENSATION MATLAB code for straincompensation.fig
%      STRAINCOMPENSATION, by itself, creates a new STRAINCOMPENSATION or raises the existing
%      singleton*.
%
%      H = STRAINCOMPENSATION returns the handle to a new STRAINCOMPENSATION or the handle to
%      the existing singleton*.
%
%      STRAINCOMPENSATION('CALLBACK',hObject,eventData,handles,...) calls the local
%      function named CALLBACK in STRAINCOMPENSATION.M with the given input arguments.
%
%      STRAINCOMPENSATION('Property','Value',...) creates a new STRAINCOMPENSATION or raises the
%      existing singleton*.  Starting from the left, property value pairs are
%      applied to the GUI before straincompensation_OpeningFcn gets called.  An
%      unrecognized property name or invalid value makes property application
%      stop.  All inputs are passed to straincompensation_OpeningFcn via varargin.
%
%      *See GUI Options on GUIDE's Tools menu.  Choose "GUI allows only one
%      instance to run (singleton)".
%
% See also: GUIDE, GUIDATA, GUIHANDLES

% Edit the above text to modify the response to help straincompensation

% Last Modified by GUIDE v2.5 10-Nov-2014 15:18:30

% Begin initialization code - DO NOT EDIT
gui_Singleton = 1;
gui_State = struct('gui_Name',       mfilename, ...
                   'gui_Singleton',  gui_Singleton, ...
                   'gui_OpeningFcn', @straincompensation_OpeningFcn, ...
                   'gui_OutputFcn',  @straincompensation_OutputFcn, ...
                   'gui_LayoutFcn',  @straincompensation_LayoutFcn, ...
                   'gui_Callback',   []);
if nargin && ischar(varargin{1})
    gui_State.gui_Callback = str2func(varargin{1});
end

if nargout
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
else
    gui_mainfcn(gui_State, varargin{:});
end
% End initialization code - DO NOT EDIT


% --- Executes just before straincompensation is made visible.
function straincompensation_OpeningFcn(hObject, eventdata, handles, varargin)
% This function has no output args, see OutputFcn.
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% varargin   command line arguments to straincompensation (see VARARGIN)

% Choose default command line output for straincompensation
handles.output = hObject;

handles.SubIIIx = 'Ga';
handles.SubIII1mx = 'Ga';
handles.SubVx = 'As';
handles.SubV1mx = 'As';

handles.QDIIIx = 'Ga';
handles.QDIII1mx = 'Ga';
handles.QDVx = 'As';
handles.QDV1mx = 'As';

handles.SCIIIx = 'Ga';
handles.SCIII1mx = 'Ga';
handles.SCVx = 'As';
handles.SCV1mx = 'As';

handles.SubX=1;
handles.SubY=1;
handles.QDX=1;
handles.QDY=1;
handles.SCX=1;
handles.SCY=1;

handles.QDDiameter=0;
handles.QDHeight=0;
handles.QDDensity=0;
handles.WLThickness=0;


% Update handles structure
guidata(hObject, handles);

% UIWAIT makes straincompensation wait for user response (see UIRESUME)
% uiwait(handles.figure1);


% --- Outputs from this function are returned to the command line.
function varargout = straincompensation_OutputFcn(hObject, eventdata, handles) 
% varargout  cell array for returning output args (see VARARGOUT);
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Get default command line output from handles structure
varargout{1} = handles.output;


% --- Executes on selection change in SubIII1mx.
function SubIII1mx_Callback(hObject, eventdata, handles)
% hObject    handle to SubIII1mx (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
contents = cellstr(get(hObject,'String'));
selected = contents{get(hObject,'Value')};
switch selected;
case ' ' % User selects peaks
	handles.SubIII1mx = 'NA';
case 'Ga' % User selects membrane
	handles.SubIII1mx = 'Ga';
case 'In' % User selects sinc
	handles.SubIII1mx = 'In';
case 'Al' % User selects sinc
	handles.SubIII1mx = 'Al';
end
guidata(hObject,handles)
% Hints: contents = cellstr(get(hObject,'String')) returns SubIII1mx contents as cell array
%        contents{get(hObject,'Value')} returns selected item from SubIII1mx


% --- Executes during object creation, after setting all properties.
function SubIII1mx_CreateFcn(hObject, eventdata, handles)
% hObject    handle to SubIII1mx (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: popupmenu controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end


% --- Executes on selection change in SubIII1mx.
function SubIIIx_Callback(hObject, eventdata, handles)
% hObject    handle to SubIII1mx (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
contents = cellstr(get(hObject,'String'));
selected = contents{get(hObject,'Value')};
switch selected;
case 'Ga' % User selects membrane
	handles.SubIIIx = 'Ga';
case 'In' % User selects sinc
	handles.SubIIIx = 'In';
case 'Al' % User selects sinc
	handles.SubIIIx = 'Al';
end
guidata(hObject,handles)
% Hints: contents = cellstr(get(hObject,'String')) returns SubIII1mx contents as cell array
%        contents{get(hObject,'Value')} returns selected item from SubIII1mx


% --- Executes during object creation, after setting all properties.
function SubIIIx_CreateFcn(hObject, eventdata, handles)
% hObject    handle to SubIII1mx (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: popupmenu controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end


% --- Executes on selection change in SubV1mx.
function SubV1mx_Callback(hObject, eventdata, handles)
% hObject    handle to SubV1mx (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
contents = cellstr(get(hObject,'String'));
selected = contents{get(hObject,'Value')};
switch selected;
case ' ' % User selects peaks
	handles.SubV1mx = 'NA';
case 'As' % User selects membrane
	handles.SubV1mx = 'As';
case 'P' % User selects sinc
	handles.SubV1mx = 'P';
case 'Sb' % User selects sinc
	handles.SubV1mx = 'Sb';
end
guidata(hObject,handles)
% Hints: contents = cellstr(get(hObject,'String')) returns SubV1mx contents as cell array
%        contents{get(hObject,'Value')} returns selected item from SubV1mx


% --- Executes during object creation, after setting all properties.
function SubV1mx_CreateFcn(hObject, eventdata, handles)
% hObject    handle to SubV1mx (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: popupmenu controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end


% --- Executes on selection change in SubV1mx.
function SubVx_Callback(hObject, eventdata, handles)
% hObject    handle to SubV1mx (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
contents = cellstr(get(hObject,'String'));
selected = contents{get(hObject,'Value')};
switch selected;
case 'As' % User selects membrane
	handles.SubVx = 'As';
case 'P' % User selects sinc
	handles.SubVx = 'P';
case 'Sb' % User selects sinc
	handles.SubVx = 'Sb';
end
guidata(hObject,handles)
% Hints: contents = cellstr(get(hObject,'String')) returns SubV1mx contents as cell array
%        contents{get(hObject,'Value')} returns selected item from SubV1mx


% --- Executes during object creation, after setting all properties.
function SubVx_CreateFcn(hObject, eventdata, handles)
% hObject    handle to SubV1mx (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: popupmenu controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end


% --- Executes on selection change in QDIIIx.
function QDIIIx_Callback(hObject, eventdata, handles)
% hObject    handle to QDIIIx (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
contents = cellstr(get(hObject,'String'));
selected = contents{get(hObject,'Value')};
switch selected;
case 'Ga' % User selects membrane
	handles.QDIIIx = 'Ga';
case 'In' % User selects sinc
	handles.QDIIIx = 'In';
case 'Al' % User selects sinc
	handles.QDIIIx = 'Al';
end
guidata(hObject,handles)
% Hints: contents = cellstr(get(hObject,'String')) returns QDIIIx contents as cell array
%        contents{get(hObject,'Value')} returns selected item from QDIIIx


% --- Executes during object creation, after setting all properties.
function QDIIIx_CreateFcn(hObject, eventdata, handles)
% hObject    handle to QDIIIx (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: popupmenu controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end


% --- Executes on selection change in QDIII1mx.
function QDIII1mx_Callback(hObject, eventdata, handles)
% hObject    handle to QDIII1mx (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
contents = cellstr(get(hObject,'String'));
selected = contents{get(hObject,'Value')};
switch selected;
case ' ' % User selects peaks
	handles.QDIII1mx = 'NA';
case 'Ga' % User selects membrane
	handles.QDIII1mx = 'Ga';
case 'In' % User selects sinc
	handles.QDIII1mx = 'In';
case 'Al' % User selects sinc
	handles.QDIII1mx = 'Al';
end
guidata(hObject,handles)
% Hints: contents = cellstr(get(hObject,'String')) returns QDIII1mx contents as cell array
%        contents{get(hObject,'Value')} returns selected item from QDIII1mx


% --- Executes during object creation, after setting all properties.
function QDIII1mx_CreateFcn(hObject, eventdata, handles)
% hObject    handle to QDIII1mx (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: popupmenu controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end


% --- Executes on selection change in QDVx.
function QDVx_Callback(hObject, eventdata, handles)
% hObject    handle to QDVx (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
contents = cellstr(get(hObject,'String'));
selected = contents{get(hObject,'Value')};
switch selected;
case 'As' % User selects membrane
	handles.QDVx = 'As';
case 'P' % User selects sinc
	handles.QDVx = 'P';
case 'Sb' % User selects sinc
	handles.QDVx = 'Sb';
end
guidata(hObject,handles)
% Hints: contents = cellstr(get(hObject,'String')) returns QDVx contents as cell array
%        contents{get(hObject,'Value')} returns selected item from QDVx


% --- Executes during object creation, after setting all properties.
function QDVx_CreateFcn(hObject, eventdata, handles)
% hObject    handle to QDVx (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: popupmenu controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end


% --- Executes on selection change in QDV1mx.
function QDV1mx_Callback(hObject, eventdata, handles)
% hObject    handle to QDV1mx (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
contents = cellstr(get(hObject,'String'));
selected = contents{get(hObject,'Value')};
switch selected;
case ' ' % User selects peaks
	handles.QDV1mx = 'NA';
case 'As' % User selects membrane
	handles.QDV1mx = 'As';
case 'P' % User selects sinc
	handles.QDV1mx = 'P';
case 'Sb' % User selects sinc
	handles.QDV1mx = 'Sb';
end
guidata(hObject,handles)
% Hints: contents = cellstr(get(hObject,'String')) returns QDV1mx contents as cell array
%        contents{get(hObject,'Value')} returns selected item from QDV1mx


% --- Executes during object creation, after setting all properties.
function QDV1mx_CreateFcn(hObject, eventdata, handles)
% hObject    handle to QDV1mx (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: popupmenu controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end


% --- Executes on selection change in SCIIIx.
function SCIIIx_Callback(hObject, eventdata, handles)
% hObject    handle to SCIIIx (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
contents = cellstr(get(hObject,'String'));
selected = contents{get(hObject,'Value')};
switch selected;
case 'Ga' % User selects membrane
	handles.SCIIIx = 'Ga';
case 'In' % User selects sinc
	handles.SCIIIx = 'In';
case 'Al' % User selects sinc
	handles.SCIIIx = 'Al';
end
guidata(hObject,handles)
% Hints: contents = cellstr(get(hObject,'String')) returns SCIIIx contents as cell array
%        contents{get(hObject,'Value')} returns selected item from SCIIIx


% --- Executes during object creation, after setting all properties.
function SCIIIx_CreateFcn(hObject, eventdata, handles)
% hObject    handle to SCIIIx (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: popupmenu controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end


% --- Executes on selection change in SCIII1mx.
function SCIII1mx_Callback(hObject, eventdata, handles)
% hObject    handle to SCIII1mx (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
contents = cellstr(get(hObject,'String'));
selected = contents{get(hObject,'Value')};
switch selected;
case ' ' % User selects peaks
	handles.SCIII1mx = 'NA';
case 'Ga' % User selects membrane
	handles.SCIII1mx = 'Ga';
case 'In' % User selects sinc
	handles.SCIII1mx = 'In';
case 'Al' % User selects sinc
	handles.SCIII1mx = 'Al';
end
guidata(hObject,handles)
% Hints: contents = cellstr(get(hObject,'String')) returns SCIII1mx contents as cell array
%        contents{get(hObject,'Value')} returns selected item from SCIII1mx


% --- Executes during object creation, after setting all properties.
function SCIII1mx_CreateFcn(hObject, eventdata, handles)
% hObject    handle to SCIII1mx (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: popupmenu controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end


% --- Executes on selection change in SCVx.
function SCVx_Callback(hObject, eventdata, handles)
% hObject    handle to SCVx (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
contents = cellstr(get(hObject,'String'));
selected = contents{get(hObject,'Value')};
switch selected;
case 'As' % User selects membrane
	handles.SCVx = 'As';
case 'P' % User selects sinc
	handles.SCVx = 'P';
case 'Sb' % User selects sinc
	handles.SCVx = 'Sb';
end
guidata(hObject,handles)
% Hints: contents = cellstr(get(hObject,'String')) returns SCVx contents as cell array
%        contents{get(hObject,'Value')} returns selected item from SCVx


% --- Executes during object creation, after setting all properties.
function SCVx_CreateFcn(hObject, eventdata, handles)
% hObject    handle to SCVx (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: popupmenu controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end


% --- Executes on selection change in SCV1mx.
function SCV1mx_Callback(hObject, eventdata, handles)
% hObject    handle to SCV1mx (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
contents = cellstr(get(hObject,'String'));
selected = contents{get(hObject,'Value')};
switch selected;
case ' ' % User selects peaks
	handles.SCV1mx = 'NA';
case 'As' % User selects membrane
	handles.SCV1mx = 'As';
case 'P' % User selects sinc
	handles.SCV1mx = 'P';
case 'Sb' % User selects sinc
	handles.SCV1mx = 'Sb';
end
guidata(hObject,handles)
% Hints: contents = cellstr(get(hObject,'String')) returns SCV1mx contents as cell array
%        contents{get(hObject,'Value')} returns selected item from SCV1mx


% --- Executes during object creation, after setting all properties.
function SCV1mx_CreateFcn(hObject, eventdata, handles)
% hObject    handle to SCV1mx (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: popupmenu controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function SubX_Callback(hObject, eventdata, handles)
% hObject    handle to SubX (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
handles.SubX=str2double(get(hObject,'String'));
guidata(hObject,handles)
% Hints: get(hObject,'String') returns contents of SubX as text
%        str2double(get(hObject,'String')) returns contents of SubX as a double


% --- Executes during object creation, after setting all properties.
function SubX_CreateFcn(hObject, eventdata, handles)
% hObject    handle to SubX (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function SubY_Callback(hObject, eventdata, handles)
% hObject    handle to SubY (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
handles.SubY=str2double(get(hObject,'String'));
guidata(hObject,handles)
% Hints: get(hObject,'String') returns contents of SubY as text
%        str2double(get(hObject,'String')) returns contents of SubY as a double


% --- Executes during object creation, after setting all properties.
function SubY_CreateFcn(hObject, eventdata, handles)
% hObject    handle to SubY (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function QDX_Callback(hObject, eventdata, handles)
% hObject    handle to QDX (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
handles.QDX=str2double(get(hObject,'String'));
guidata(hObject,handles)
% Hints: get(hObject,'String') returns contents of QDX as text
%        str2double(get(hObject,'String')) returns contents of QDX as a double


% --- Executes during object creation, after setting all properties.
function QDX_CreateFcn(hObject, eventdata, handles)
% hObject    handle to QDX (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function QDY_Callback(hObject, eventdata, handles)
% hObject    handle to QDY (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
handles.QDY=str2double(get(hObject,'String'));
guidata(hObject,handles)
% Hints: get(hObject,'String') returns contents of QDY as text
%        str2double(get(hObject,'String')) returns contents of QDY as a double


% --- Executes during object creation, after setting all properties.
function QDY_CreateFcn(hObject, eventdata, handles)
% hObject    handle to QDY (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function SCX_Callback(hObject, eventdata, handles)
% hObject    handle to SCX (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
handles.SCX=str2double(get(hObject,'String'));
guidata(hObject,handles)
% Hints: get(hObject,'String') returns contents of SCX as text
%        str2double(get(hObject,'String')) returns contents of SCX as a double


% --- Executes during object creation, after setting all properties.
function SCX_CreateFcn(hObject, eventdata, handles)
% hObject    handle to SCX (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function SCY_Callback(hObject, eventdata, handles)
% hObject    handle to SCY (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
handles.SCY=str2double(get(hObject,'String'));
guidata(hObject,handles)
% Hints: get(hObject,'String') returns contents of SCY as text
%        str2double(get(hObject,'String')) returns contents of SCY as a double


% --- Executes during object creation, after setting all properties.
function SCY_CreateFcn(hObject, eventdata, handles)
% hObject    handle to SCY (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function QDDiameter_Callback(hObject, eventdata, handles)
% hObject    handle to QDDiameter (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
handles.QDDiameter=str2double(get(hObject,'String'));
guidata(hObject,handles)
% Hints: get(hObject,'String') returns contents of QDDiameter as text
%        str2double(get(hObject,'String')) returns contents of QDDiameter as a double


% --- Executes during object creation, after setting all properties.
function QDDiameter_CreateFcn(hObject, eventdata, handles)
% hObject    handle to QDDiameter (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function QDHeight_Callback(hObject, eventdata, handles)
% hObject    handle to QDHeight (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
handles.QDHeight=str2double(get(hObject,'String'));
guidata(hObject,handles)
% Hints: get(hObject,'String') returns contents of QDHeight as text
%        str2double(get(hObject,'String')) returns contents of QDHeight as a double


% --- Executes during object creation, after setting all properties.
function QDHeight_CreateFcn(hObject, eventdata, handles)
% hObject    handle to QDHeight (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function QDDensity_Callback(hObject, eventdata, handles)
% hObject    handle to QDDensity (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
handles.QDDensity=str2double(get(hObject,'String'));
guidata(hObject,handles)
% Hints: get(hObject,'String') returns contents of QDDensity as text
%        str2double(get(hObject,'String')) returns contents of QDDensity as a double


% --- Executes during object creation, after setting all properties.
function QDDensity_CreateFcn(hObject, eventdata, handles)
% hObject    handle to QDDensity (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function WLThickness_Callback(hObject, eventdata, handles)
% hObject    handle to WLThickness (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
handles.WLThickness=str2double(get(hObject,'String'));
guidata(hObject,handles)
% Hints: get(hObject,'String') returns contents of WLThickness as text
%        str2double(get(hObject,'String')) returns contents of WLThickness as a double


% --- Executes during object creation, after setting all properties.
function WLThickness_CreateFcn(hObject, eventdata, handles)
% hObject    handle to WLThickness (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end


% --- Executes on button press in calculate.
function calculate_Callback(hObject, eventdata, handles)
% hObject    handle to calculate (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

if handles.SubX < 1
    if handles.SubY < 1
        %eg AlGaAsP
        aA=getMaterial(handles.SubIIIx, handles.SubVx); %AlAs
        aB=getMaterial(handles.SubIII1mx, handles.SubVx); %GaAs
        aC=getMaterial(handles.SubIIIx, handles.SubV1mx); %AlP
        aD=getMaterial(handles.SubIII1mx, handles.SubV1mx); %GaP
        [aSub,c11Sub,c12Sub]=calcMaterial(aA, aB, handles.SubX, aC, aD, handles.SubY);
    else
        %eg AlGaAs
        aA=getMaterial(handles.SubIIIx, handles.SubVx);
        aB=getMaterial(handles.SubIII1mx, handles.SubVx);
        [aSub,c11Sub,c12Sub]=calcMaterial(aA, aB, handles.SubX, 0, 0, 0);
    end
elseif handles.SubY < 1
    %eg GaAsP
    aC=getMaterial(handles.SubIIIx, handles.SubVx);
    aD=getMaterial(handles.SubIIIx, handles.SubV1mx);
    [aSub,c11Sub,c12Sub]=calcMaterial(0, 0, 0, aC, aD, handles.SubY);
else
    %eg GaAs
    [aSub,c11Sub,c12Sub]=getMaterial(handles.SubIIIx, handles.SubVx);
end

if handles.QDX < 1
    if handles.QDY < 1
        %eg AlGaAsP
        bA=getMaterial(handles.QDIIIx, handles.QDVx); %AlAs
        bB=getMaterial(handles.QDIII1mx, handles.QDVx); %GaAs
        bC=getMaterial(handles.QDIIIx, handles.QDV1mx); %AlP
        bD=getMaterial(handles.QDIII1mx, handles.QDV1mx); %GaP
        [aQD,c11QD,c12QD]=calcMaterial(bA, bB, handles.QDX, bC, bD, handles.QDY);
    else
        %eg AlGaAs
        bA=getMaterial(handles.QDIIIx, handles.QDVx);
        bB=getMaterial(handles.QDIII1mx, handles.QDVx);
        [aQD,c11QD,c12QD]=calcMaterial(bA, bB, handles.QDX, 0, 0, 0);
    end
elseif handles.QDY < 1
    %eg GaAsP
    bC=getMaterial(handles.QDIIIx, handles.QDVx);
    bD=getMaterial(handles.QDIIIx, handles.QDV1mx);
    [aQD,c11QD,c12QD]=calcMaterial(0, 0, 0, bC, bD, handles.QDY);
else
    %eg GaAs
    [aQD,c11QD,c12QD]=getMaterial(handles.QDIIIx, handles.QDVx);
end

if handles.SCX < 1
    if handles.SCY < 1
        %eg AlGaAsP
        cA=getMaterial(handles.SCIIIx, handles.SCVx); %AlAs
        cB=getMaterial(handles.SCIII1mx, handles.SCVx); %GaAs
        cC=getMaterial(handles.SCIIIx, handles.SCV1mx); %AlP
        cD=getMaterial(handles.SCIII1mx, handles.SCV1mx); %GaP
        [aSC,c11SC,c12SC]=calcMaterial(cA, cB, handles.SCX, cC, cD, handles.SCY);
    else
        %eg AlGaAs
        cA=getMaterial(handles.SCIIIx, handles.SCVx);
        cB=getMaterial(handles.SCIII1mx, handles.SCVx);
        [aSC,c11SC,c12SC]=calcMaterial(cA, cB, handles.SCX, 0, 0, 0);
    end
elseif handles.SCY < 1
    %eg GaAsP
    cC=getMaterial(handles.SCIIIx, handles.SCVx);
    cD=getMaterial(handles.SCIIIx, handles.SCV1mx);
    [aSC,c11SC,c12SC]=calcMaterial(0, 0, 0, cC, cD, handles.SCY);
else
    %eg GaAs
    [aSC,c11SC,c12SC]=getMaterial(handles.SCIIIx, handles.SCVx);
end
%[aQD, c11QD, c12QD]=getMaterial(handles.QDIIIx, handles.QDVx); 
%[aSC, c11SC, c12SC]=getMaterial(handles.SCIIIx, handles.SCVx);

QDDensity=handles.QDDensity * 1e-16; %Angstrom^-2 {5e-6 A^-2 = 5e10 cm^-2}
QDDiameter=handles.QDDiameter * 10; %Angstrom
QDHeight=handles.QDHeight * 10; %Angstrom
WLThickness=handles.WLThickness * 10;

ASC=c11SC + c12SC - (2*c12SC.^2./c11SC);
AQD=c11QD + c12QD - (2*c12QD.^2./c11QD);

%Leonard QD as spherical cap
vQDSphCap=pi.*QDHeight./6 .* (3 .*(QDDiameter/2).^2 + QDHeight.^2);

%CET
CETQD=QDHeight*((AQD .* aSC^2 .* (aSub - aQD))./(ASC .* aQD^2 .* (aSC - aSub)))/10;

%mCETCyl
CETWL=WLThickness*((AQD .* aSC^2 .* (aSub - aQD))./(ASC .* aQD^2 .* (aSC - aSub)))/10;
QDsigma=(QDDiameter/2)^2*pi; %QD base area
vQDCyl=QDHeight*QDsigma;
tQDWLCyl=(QDsigma*QDDensity)*QDHeight+(1-QDsigma*QDDensity)*WLThickness;
mCETcyl=(QDsigma*QDDensity)*CETQD + (1-QDsigma*QDDensity)*CETWL; %weighted SC thickness

%mCETSphere
vQDOblSph=((4/3)*pi*(QDDiameter/2)^2*QDHeight)/2;
tQD=vQDOblSph*QDDensity; %volume of QD times QD density gives average thickness of QD per area
tQDWL=WLThickness+tQD; %WL is treated as external to QD
mCETsph=tQDWL*((AQD .* aSC^2 .* (aSub - aQD))./(ASC .* aQD^2 .* (aSC - aSub)))/10;

set(handles.QDVolSphCap,'String',num2str(vQDSphCap/1000,4)) %convert to nm^3 from A^3
set(handles.QDVolCyl,'String',num2str(vQDCyl/1000,4)) %convert to nm^3 from A^3
set(handles.QDVolOblSph,'String',num2str(vQDOblSph/1000,4)) %convert to nm^3 from A^3

set(handles.QDCoverageQW,'String',num2str(QDHeight/10,4)) %convert to nm^3 cm^-2 from A^3 cm^-2
set(handles.QDCoverageCyl,'String',num2str(tQDWLCyl/10,4))
set(handles.QDCoverageOblSph,'String',num2str(tQDWL/10,4))

set(handles.CET,'String',num2str(CETQD,4))
set(handles.MCETCyl,'String',num2str(mCETcyl,4))
set(handles.MCETSphere,'String',num2str(mCETsph,4))

set(handles.aSub,'String',num2str(aSub))
set(handles.aQD,'String',num2str(aQD))
set(handles.aSC,'String',num2str(aSC))

set(handles.C11Sub,'String',num2str(c11Sub,4))
set(handles.C11QD,'String',num2str(c11QD,4))
set(handles.C11SC,'String',num2str(c11SC,4))

set(handles.C12Sub,'String',num2str(c12Sub,4))
set(handles.C12QD,'String',num2str(c12QD,4))
set(handles.C12SC,'String',num2str(c12SC,4))

guidata(hObject,handles)

function [a,C11,C12]=getMaterial(III,V)
%All material properties from:
% [1]I. Vurgaftman, J. R. Meyer, and L. R. Ram-Mohan, “Band parameters 
% for III–V compound semiconductors and their alloys,” Journal of Applied 
% Physics, vol. 89, no. 11, pp. 5815–5875, Jun. 2001.
 
switch III
    case 'Ga'
        switch V
            case 'As'
                %GaAs
                a=5.65325; %[Angstrom]
                C11=1221; %[GPa]
                C12=566; %[GPa]
            case 'P'
                %GaP
                a=5.4505; %[Angstrom]
                C11=1405; %[GPa]
                C12=620.3; %[GPa]
            case 'Sb'
                %GaSb
                a=6.0959; %[Angstrom]
                C11=884.2; %[GPa]
                C12=402.6; %[GPa]
        end
    case 'In'
        switch V
            case 'As'
                %InAs
                a=6.0583; %[Angstrom]
                C11=832.9; %[GPa]
                C12=452.6; %[GPa]
            case 'P'
                %InP
                a=5.8697; %[Angstrom]
                C11=1011; %[GPa]
                C12=561; %[GPa]
            case 'Sb' 
                %InSb
                a=6.4794; %[Angstrom]
                C11=684.7; %[GPa]
                C12=373.5; %[GPa]
        end
    case 'Al'
        switch V
            case 'As'
                %AlAs
                a=5.6611; %[Angstrom]
                C11=1250; %[GPa]
                C12=534; %[GPa]
            case 'P'
                %AlP
                a=5.4672; %[Angstrom]
                C11=1330; %[GPa]
                C12=630; %[GPa]
            case 'Sb'
                %AlSb
                a=6.1355; %[Angstrom]
                C11=876.9; %[GPa]
                C12=434.1; %[GPa]
        end
end

function [a,C11,C12]=calcMaterial(ac,bc,x,ad,bd,y)
if x > 0
    if y > 0
        %eg AlGaAsP
        a=(x*y)*ac+x*(1-y)*ad+(1-x)*y*bc+(1-x)*(1-y)*bd;
    else
        %eg AlGaP
        a=(ac)*x + (bc)*(1-x);
    end
else
    %eg GaAsP
    a=(ad)*y + (bd)*(1-y);
end
%[1]S. Adachi, Properties of group-IV, III-V and II-VI semiconductors. 
%   Chichester, England; Hoboken, NJ: John Wiley & Sons, 2005.
C11=exp((-4.16629.*log(a)+9.70098))*100; %[GPa] 
C12=exp((-3.10462.*log(a)+7.10375))*100; %[GPa]


% --- Creates and returns a handle to the GUI figure. 
function h1 = straincompensation_LayoutFcn(policy)
% policy - create a new figure or use a singleton. 'new' or 'reuse'.

persistent hsingleton;
if strcmpi(policy, 'reuse') & ishandle(hsingleton)
    h1 = hsingleton;
    return;
end

appdata = [];
appdata.GUIDEOptions = struct(...
    'active_h', [], ...
    'taginfo', struct(...
    'figure', 2, ...
    'uipanel', 5, ...
    'popupmenu', 14, ...
    'text', 82, ...
    'edit', 12, ...
    'pushbutton', 2), ...
    'override', 0, ...
    'release', 13, ...
    'resize', 'none', ...
    'accessibility', 'callback', ...
    'mfile', 1, ...
    'callbacks', 1, ...
    'singleton', 1, ...
    'syscolorfig', 1, ...
    'blocking', 0, ...
    'lastSavedFile', 'C:\Users\sjp5958\Documents\MATLAB\straincompensation_git\straincompensation.m', ...
    'lastFilename', 'C:\Users\sjp5958\Documents\MATLAB\sc.fig');
appdata.lastValidTag = 'figure1';
appdata.GUIDELayoutEditor = [];
appdata.initTags = struct(...
    'handle', [], ...
    'tag', 'figure1');

h1 = figure(...
'Units','characters',...
'Color',[0.941176470588235 0.941176470588235 0.941176470588235],...
'Colormap',[0 0 0.5625;0 0 0.625;0 0 0.6875;0 0 0.75;0 0 0.8125;0 0 0.875;0 0 0.9375;0 0 1;0 0.0625 1;0 0.125 1;0 0.1875 1;0 0.25 1;0 0.3125 1;0 0.375 1;0 0.4375 1;0 0.5 1;0 0.5625 1;0 0.625 1;0 0.6875 1;0 0.75 1;0 0.8125 1;0 0.875 1;0 0.9375 1;0 1 1;0.0625 1 1;0.125 1 0.9375;0.1875 1 0.875;0.25 1 0.8125;0.3125 1 0.75;0.375 1 0.6875;0.4375 1 0.625;0.5 1 0.5625;0.5625 1 0.5;0.625 1 0.4375;0.6875 1 0.375;0.75 1 0.3125;0.8125 1 0.25;0.875 1 0.1875;0.9375 1 0.125;1 1 0.0625;1 1 0;1 0.9375 0;1 0.875 0;1 0.8125 0;1 0.75 0;1 0.6875 0;1 0.625 0;1 0.5625 0;1 0.5 0;1 0.4375 0;1 0.375 0;1 0.3125 0;1 0.25 0;1 0.1875 0;1 0.125 0;1 0.0625 0;1 0 0;0.9375 0 0;0.875 0 0;0.8125 0 0;0.75 0 0;0.6875 0 0;0.625 0 0;0.5625 0 0],...
'IntegerHandle','off',...
'InvertHardcopy',get(0,'defaultfigureInvertHardcopy'),...
'MenuBar','none',...
'Name','sc',...
'NumberTitle','off',...
'PaperPosition',get(0,'defaultfigurePaperPosition'),...
'Position',[103.8 26.7692307692308 104 34.8461538461538],...
'Resize','off',...
'HandleVisibility','callback',...
'UserData',[],...
'Tag','figure1',...
'Visible','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'uipanel1';

h2 = uipanel(...
'Parent',h1,...
'Units','characters',...
'Title','Material Systems',...
'Clipping','on',...
'Position',[1.6 13.9230769230769 51.6 20.1538461538462],...
'Tag','uipanel1',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'SubIIIx';

h3 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)straincompensation('SubIIIx_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[8.4 14.6923076923077 7.8 1.92307692307692],...
'String',{  'Ga'; 'In'; 'Al' },...
'Style','popupmenu',...
'Value',1,...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)straincompensation('SubIIIx_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','SubIIIx');

appdata = [];
appdata.lastValidTag = 'SubIII1mx';

h4 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)straincompensation('SubIII1mx_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[18.4 14.6923076923077 7.8 1.92307692307692],...
'String',{  'Ga'; 'In'; 'Al' },...
'Style','popupmenu',...
'Value',1,...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)straincompensation('SubIII1mx_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','SubIII1mx');

appdata = [];
appdata.lastValidTag = 'SubVx';

h5 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)straincompensation('SubVx_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[28.4 14.6923076923077 7.8 1.92307692307692],...
'String',{  'As'; 'P'; 'Sb' },...
'Style','popupmenu',...
'Value',1,...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)straincompensation('SubVx_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','SubVx');

appdata = [];
appdata.lastValidTag = 'SubV1mx';

h6 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)straincompensation('SubV1mx_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[38.4 14.6923076923077 7.8 1.92307692307692],...
'String',{  'As'; 'P'; 'Sb' },...
'Style','popupmenu',...
'Value',1,...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)straincompensation('SubV1mx_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','SubV1mx');

appdata = [];
appdata.lastValidTag = 'text1';

h7 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'Position',[6.2 16.6153846153846 10.4 1.07692307692308],...
'String','Substrate',...
'Style','text',...
'Tag','text1',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'QDIIIx';

h8 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)straincompensation('QDIIIx_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[8.4 9 7.8 1.92307692307692],...
'String',{  'Ga'; 'In'; 'Al' },...
'Style','popupmenu',...
'Value',1,...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)straincompensation('QDIIIx_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','QDIIIx');

appdata = [];
appdata.lastValidTag = 'QDIII1mx';

h9 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)straincompensation('QDIII1mx_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[18.4 9 7.8 1.92307692307692],...
'String',{  'Ga'; 'In'; 'Al' },...
'Style','popupmenu',...
'Value',1,...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)straincompensation('QDIII1mx_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','QDIII1mx');

appdata = [];
appdata.lastValidTag = 'QDVx';

h10 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)straincompensation('QDVx_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[28.4 9 7.8 1.92307692307692],...
'String',{  'As'; 'P'; 'Sb' },...
'Style','popupmenu',...
'Value',1,...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)straincompensation('QDVx_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','QDVx');

appdata = [];
appdata.lastValidTag = 'QDV1mx';

h11 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)straincompensation('QDV1mx_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[38.4 9 7.8 1.92307692307692],...
'String',{  'As'; 'P'; 'Sb' },...
'Style','popupmenu',...
'Value',1,...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)straincompensation('QDV1mx_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','QDV1mx');

appdata = [];
appdata.lastValidTag = 'SCIIIx';

h12 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)straincompensation('SCIIIx_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[8.4 3.23076923076923 7.8 1.92307692307692],...
'String',{  'Ga'; 'In'; 'Al' },...
'Style','popupmenu',...
'Value',1,...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)straincompensation('SCIIIx_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','SCIIIx');

appdata = [];
appdata.lastValidTag = 'SCIII1mx';

h13 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)straincompensation('SCIII1mx_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[18.4 3.23076923076923 7.8 1.92307692307692],...
'String',{  'Ga'; 'In'; 'Al' },...
'Style','popupmenu',...
'Value',1,...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)straincompensation('SCIII1mx_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','SCIII1mx');

appdata = [];
appdata.lastValidTag = 'SCVx';

h14 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)straincompensation('SCVx_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[28.4 3.23076923076923 7.8 1.92307692307692],...
'String',{  'As'; 'P'; 'Sb' },...
'Style','popupmenu',...
'Value',1,...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)straincompensation('SCVx_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','SCVx');

appdata = [];
appdata.lastValidTag = 'SCV1mx';

h15 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)straincompensation('SCV1mx_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[38.4 3.23076923076923 7.8 1.92307692307692],...
'String',{  'As'; 'P'; 'Sb' },...
'Style','popupmenu',...
'Value',1,...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)straincompensation('SCV1mx_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','SCV1mx');

appdata = [];
appdata.lastValidTag = 'text2';

h16 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'Position',[6.2 11.0769230769231 13 1.07692307692308],...
'String','Quantum Dot',...
'Style','text',...
'Tag','text2',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text3';

h17 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'Position',[6.2 5.15384615384615 20.6 1.07692307692308],...
'String','Strain Compensation',...
'Style','text',...
'Tag','text3',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'SubX';

h18 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)straincompensation('SubX_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[10.4 13 5.8 1.76923076923077],...
'String','1',...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)straincompensation('SubX_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','SubX');

appdata = [];
appdata.lastValidTag = 'text4';

h19 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'Position',[7 13.1538461538462 3.2 1.46153846153846],...
'String','x:',...
'Style','text',...
'Tag','text4',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'SubY';

h20 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)straincompensation('SubY_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[30.2 13 6 1.76923076923077],...
'String','1',...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)straincompensation('SubY_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','SubY');

appdata = [];
appdata.lastValidTag = 'text5';

h21 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'Position',[26.8 13.1538461538462 3.2 1.46153846153846],...
'String','y:',...
'Style','text',...
'Tag','text5',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'QDX';

h22 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)straincompensation('QDX_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[10.6 7.23076923076923 5.6 1.76923076923077],...
'String','1',...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)straincompensation('QDX_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','QDX');

appdata = [];
appdata.lastValidTag = 'text6';

h23 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'Position',[7.2 7.38461538461539 3.2 1.46153846153846],...
'String','x:',...
'Style','text',...
'Tag','text6',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'QDY';

h24 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)straincompensation('QDY_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[30.2 7.23076923076923 6 1.76923076923077],...
'String','1',...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)straincompensation('QDY_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','QDY');

appdata = [];
appdata.lastValidTag = 'text7';

h25 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'Position',[26.8 7.38461538461539 3.2 1.46153846153846],...
'String','y:',...
'Style','text',...
'Tag','text7',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'SCX';

h26 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)straincompensation('SCX_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[10.4 1.38461538461538 5.8 1.76923076923077],...
'String','1',...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)straincompensation('SCX_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','SCX');

appdata = [];
appdata.lastValidTag = 'text8';

h27 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'Position',[7 1.53846153846154 3.2 1.46153846153846],...
'String','x:',...
'Style','text',...
'Tag','text8',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'SCY';

h28 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)straincompensation('SCY_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[30.2 1.38461538461538 6 1.76923076923077],...
'String','1',...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)straincompensation('SCY_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','SCY');

appdata = [];
appdata.lastValidTag = 'text9';

h29 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'Position',[26.8 1.53846153846154 3.2 1.46153846153846],...
'String','y:',...
'Style','text',...
'Tag','text9',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text49';

h30 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'Position',[19.8 13.3846153846154 5 1.07692307692308],...
'String','(1-x)',...
'Style','text',...
'Tag','text49',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text50';

h31 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'Position',[40.2 13.3846153846154 5 1.07692307692308],...
'String','(1-y)',...
'Style','text',...
'Tag','text50',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text51';

h32 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'Position',[19.8 7.61538461538462 5 1.07692307692308],...
'String','(1-x)',...
'Style','text',...
'Tag','text51',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text52';

h33 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'Position',[19.8 1.76923076923077 5 1.07692307692308],...
'String','(1-x)',...
'Style','text',...
'Tag','text52',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text53';

h34 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'Position',[40.2 7.61538461538462 5 1.07692307692308],...
'String','(1-y)',...
'Style','text',...
'Tag','text53',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text54';

h35 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'Position',[40.2 1.76923076923077 5 1.07692307692308],...
'String','(1-y)',...
'Style','text',...
'Tag','text54',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'uipanel2';

h36 = uipanel(...
'Parent',h1,...
'Units','characters',...
'Title','QD Properties',...
'Clipping','on',...
'Position',[53.8 19.9230769230769 50.4 14.1538461538462],...
'Tag','uipanel2',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text10';

h37 = uicontrol(...
'Parent',h36,...
'Units','characters',...
'Position',[3.4 11.3076923076923 13.4 1.07692307692308],...
'String','QD Diameter:',...
'Style','text',...
'Tag','text10',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text11';

h38 = uicontrol(...
'Parent',h36,...
'Units','characters',...
'Position',[6.4 9.69230769230771 10.4 1.07692307692308],...
'String','QD Height:',...
'Style','text',...
'Tag','text11',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text12';

h39 = uicontrol(...
'Parent',h36,...
'Units','characters',...
'Position',[4 8.07692307692308 12.8 1.07692307692308],...
'String','QD Density:',...
'Style','text',...
'Tag','text12',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text13';

h40 = uicontrol(...
'Parent',h36,...
'Units','characters',...
'Position',[1.8 6.46153846153846 15 1.07692307692308],...
'String','WL Thickness:',...
'Style','text',...
'Tag','text13',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'QDDiameter';

h41 = uicontrol(...
'Parent',h36,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)straincompensation('QDDiameter_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[17.2 11.1538461538462 12.4 1.30769230769231],...
'String','0',...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)straincompensation('QDDiameter_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','QDDiameter');

appdata = [];
appdata.lastValidTag = 'QDHeight';

h42 = uicontrol(...
'Parent',h36,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)straincompensation('QDHeight_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[17.2 9.53846153846155 12.4 1.30769230769231],...
'String','0',...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)straincompensation('QDHeight_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','QDHeight');

appdata = [];
appdata.lastValidTag = 'QDDensity';

h43 = uicontrol(...
'Parent',h36,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)straincompensation('QDDensity_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[17.2 7.92307692307693 12.4 1.30769230769231],...
'String','0',...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)straincompensation('QDDensity_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','QDDensity');

appdata = [];
appdata.lastValidTag = 'WLThickness';

h44 = uicontrol(...
'Parent',h36,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)straincompensation('WLThickness_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[17.2 6.3076923076923 12.4 1.30769230769231],...
'String','0',...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)straincompensation('WLThickness_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','WLThickness');

appdata = [];
appdata.lastValidTag = 'text14';

h45 = uicontrol(...
'Parent',h36,...
'Units','characters',...
'Position',[30 11.3076923076923 5.8 1.07692307692308],...
'String','[nm]',...
'Style','text',...
'Tag','text14',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text15';

h46 = uicontrol(...
'Parent',h36,...
'Units','characters',...
'Position',[30 9.69230769230771 5.8 1.07692307692308],...
'String','[nm]',...
'Style','text',...
'Tag','text15',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text16';

h47 = uicontrol(...
'Parent',h36,...
'Units','characters',...
'Position',[30 8.07692307692308 8.8 1.07692307692308],...
'String','[cm^-2]',...
'Style','text',...
'Tag','text16',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text17';

h48 = uicontrol(...
'Parent',h36,...
'Units','characters',...
'Position',[30 6.46153846153846 5.8 1.07692307692308],...
'String','[nm]',...
'Style','text',...
'Tag','text17',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text55';

h49 = uicontrol(...
'Parent',h36,...
'Units','characters',...
'Position',[1.8 4.15384615384615 19.2 1.07692307692308],...
'String','QD Vol (Sph. Cap):',...
'Style','text',...
'Tag','text55',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text56';

h50 = uicontrol(...
'Parent',h36,...
'Units','characters',...
'Position',[34.6000000000001 4.15384615384615 6.4 1.07692307692308],...
'String','[nm^3]',...
'Style','text',...
'Tag','text56',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'QDVolSphCap';

h51 = uicontrol(...
'Parent',h36,...
'Units','characters',...
'Position',[21.6 4 11.8 1.23076923076923],...
'String','0',...
'Style','text',...
'Tag','QDVolSphCap',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text58';

h52 = uicontrol(...
'Parent',h36,...
'Units','characters',...
'Position',[1.8 2.76923076923077 19.2 1.07692307692308],...
'String','QD Vol (Cylinder):',...
'Style','text',...
'Tag','text58',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text59';

h53 = uicontrol(...
'Parent',h36,...
'Units','characters',...
'Position',[34.6000000000001 2.76923076923077 6.4 1.07692307692308],...
'String','[nm^3]',...
'Style','text',...
'Tag','text59',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'QDVolCyl';

h54 = uicontrol(...
'Parent',h36,...
'Units','characters',...
'Position',[21.6 2.61538461538462 11.8 1.23076923076923],...
'String','0',...
'Style','text',...
'Tag','QDVolCyl',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text61';

h55 = uicontrol(...
'Parent',h36,...
'Units','characters',...
'Position',[1.8 1.38461538461538 19.2 1.07692307692308],...
'String','QD Vol (Obl. Sph.):',...
'Style','text',...
'Tag','text61',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text62';

h56 = uicontrol(...
'Parent',h36,...
'Units','characters',...
'Position',[34.6 1.38461538461538 6.4 1.07692307692308],...
'String','[nm^3]',...
'Style','text',...
'Tag','text62',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'QDVolOblSph';

h57 = uicontrol(...
'Parent',h36,...
'Units','characters',...
'Position',[21.6 1.23076923076923 11.8 1.23076923076923],...
'String','0',...
'Style','text',...
'Tag','QDVolOblSph',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'uipanel3';

h58 = uipanel(...
'Parent',h1,...
'Units','characters',...
'Title','Strain Compensation',...
'Clipping','on',...
'Position',[54.2 3.92307692307692 50 15.6923076923077],...
'Tag','uipanel3',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text18';

h59 = uicontrol(...
'Parent',h58,...
'Units','characters',...
'Position',[2.6 9.76923076923077 23.8 1.15384615384615],...
'String','CET (QD Height as QW)',...
'Style','text',...
'Tag','text18',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'CET';

h60 = uicontrol(...
'Parent',h58,...
'Units','characters',...
'Position',[5.2 8.61538461538462 17 1.15384615384615],...
'String','0',...
'Style','text',...
'Tag','CET',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text20';

h61 = uicontrol(...
'Parent',h58,...
'Units','characters',...
'Position',[22.6 8.69230769230769 5.8 1.07692307692308],...
'String','[nm]',...
'Style','text',...
'Tag','text20',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text21';

h62 = uicontrol(...
'Parent',h58,...
'Units','characters',...
'Position',[2.4 6.23076923076923 30.4 1.07692307692308],...
'String','Modified CET (QD as Cylinder)',...
'Style','text',...
'Tag','text21',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'MCETCyl';

h63 = uicontrol(...
'Parent',h58,...
'Units','characters',...
'Position',[3.6 5.07692307692308 20 1.15384615384615],...
'String','0',...
'Style','text',...
'Tag','MCETCyl',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text24';

h64 = uicontrol(...
'Parent',h58,...
'Units','characters',...
'Position',[22.6 5.30769230769231 5.8 1.07692307692308],...
'String','[nm]',...
'Style','text',...
'Tag','text24',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text25';

h65 = uicontrol(...
'Parent',h58,...
'Units','characters',...
'Position',[2.2 2.84615384615385 43.2 1.07692307692308],...
'String','Modified CET (QD as Oblate-Hemispheroid)',...
'Style','text',...
'Tag','text25',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'MCETSphere';

h66 = uicontrol(...
'Parent',h58,...
'Units','characters',...
'Position',[5.4 1.69230769230769 17 1.15384615384615],...
'String','0',...
'Style','text',...
'Tag','MCETSphere',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text27';

h67 = uicontrol(...
'Parent',h58,...
'Units','characters',...
'Position',[22.6 1.76923076923077 5.8 1.07692307692308],...
'String','[nm]',...
'Style','text',...
'Tag','text27',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'calculate';

h68 = uicontrol(...
'Parent',h58,...
'Units','characters',...
'Callback',@(hObject,eventdata)straincompensation('calculate_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[33.2 12.3846153846154 14.6 1.76923076923077],...
'String','Calculate',...
'Tag','calculate',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text72';

h69 = uicontrol(...
'Parent',h58,...
'Units','characters',...
'Position',[23.2 0.615384615384615 20.6 1.07692307692308],...
'String','[nm^3 cm^-2] or [nm]',...
'Style','text',...
'Tag','text72',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text73';

h70 = uicontrol(...
'Parent',h58,...
'Units','characters',...
'Position',[5.8 10.8461538461538 29.6 1.46153846153846],...
'String','Effective QD + WL Thickness',...
'Style','text',...
'Tag','text73',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text74';

h71 = uicontrol(...
'Parent',h58,...
'Units','characters',...
'Position',[5.8 12.0769230769231 23.8 1.46153846153846],...
'String','Required SC Thickness',...
'Style','text',...
'Tag','text74',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'QDCoverageOblSph';

h72 = uicontrol(...
'Parent',h58,...
'Units','characters',...
'Position',[5.4 0.538461538461539 17 1.15384615384615],...
'String','0',...
'Style','text',...
'Tag','QDCoverageOblSph',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text76';

h73 = uicontrol(...
'Parent',h58,...
'Units','characters',...
'Position',[23.2 4.15384615384615 20.6 1.07692307692308],...
'String','[nm^3 cm^-2] or [nm]',...
'Style','text',...
'Tag','text76',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'QDCoverageCyl';

h74 = uicontrol(...
'Parent',h58,...
'Units','characters',...
'Position',[3.6 3.84615384615385 20 1.15384615384615],...
'String','0',...
'Style','text',...
'Tag','QDCoverageCyl',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'QDCoverageQW';

h75 = uicontrol(...
'Parent',h58,...
'Units','characters',...
'Position',[5.2 7.46153846153847 17 1.15384615384615],...
'String','0',...
'Style','text',...
'Tag','QDCoverageQW',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text79';

h76 = uicontrol(...
'Parent',h58,...
'Units','characters',...
'Position',[23.2 7.53846153846154 20.6 1.07692307692308],...
'String','[nm^3 cm^-2] or [nm]',...
'Style','text',...
'Tag','text79',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'uipanel4';

h77 = uipanel(...
'Parent',h1,...
'Units','characters',...
'Title','Literature or Calculated Values',...
'Clipping','on',...
'Position',[1.6 5.76923076923077 51.4 8],...
'Tag','uipanel4',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text28';

h78 = uicontrol(...
'Parent',h77,...
'Units','characters',...
'Position',[1.2 4.15384615384615 5 1.15384615384615],...
'String','Sub',...
'Style','text',...
'Tag','text28',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text29';

h79 = uicontrol(...
'Parent',h77,...
'Units','characters',...
'Position',[1.6 2.69230769230769 4.6 1.07692307692308],...
'String','QD',...
'Style','text',...
'Tag','text29',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text30';

h80 = uicontrol(...
'Parent',h77,...
'Units','characters',...
'Position',[1 1.15384615384615 5.2 1.07692307692308],...
'String','SC',...
'Style','text',...
'Tag','text30',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text31';

h81 = uicontrol(...
'Parent',h77,...
'Units','characters',...
'Position',[7.2 5.61538461538462 13 1.07692307692308],...
'String','a [Angstrom]',...
'Style','text',...
'Tag','text31',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text32';

h82 = uicontrol(...
'Parent',h77,...
'Units','characters',...
'Position',[20.2 5.61538461538462 15.6 1.07692307692308],...
'String','C11 [GPa]',...
'Style','text',...
'Tag','text32',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text33';

h83 = uicontrol(...
'Parent',h77,...
'Units','characters',...
'Position',[35.4 5.61538461538462 14.2 1.07692307692308],...
'String','C12 [GPa]',...
'Style','text',...
'Tag','text33',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'aSub';

h84 = uicontrol(...
'Parent',h77,...
'Units','characters',...
'Position',[8.40000000000001 4.07692307692308 10.4 1.07692307692308],...
'String','0',...
'Style','text',...
'Tag','aSub',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'aQD';

h85 = uicontrol(...
'Parent',h77,...
'Units','characters',...
'Position',[8.40000000000001 2.53846153846154 10.4 1.07692307692308],...
'String','0',...
'Style','text',...
'Tag','aQD',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'aSC';

h86 = uicontrol(...
'Parent',h77,...
'Units','characters',...
'Position',[8.40000000000001 1 10.4 1.07692307692308],...
'String','0',...
'Style','text',...
'Tag','aSC',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'C11Sub';

h87 = uicontrol(...
'Parent',h77,...
'Units','characters',...
'Position',[22 4.07692307692308 10.4 1.07692307692308],...
'String','0',...
'Style','text',...
'Tag','C11Sub',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'C11QD';

h88 = uicontrol(...
'Parent',h77,...
'Units','characters',...
'Position',[22 2.53846153846154 10.4 1.07692307692308],...
'String','0',...
'Style','text',...
'Tag','C11QD',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'C11SC';

h89 = uicontrol(...
'Parent',h77,...
'Units','characters',...
'Position',[22 1 10.4 1.07692307692308],...
'String','0',...
'Style','text',...
'Tag','C11SC',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'C12Sub';

h90 = uicontrol(...
'Parent',h77,...
'Units','characters',...
'Position',[36.6 4.07692307692308 10.4 1.07692307692308],...
'String','0',...
'Style','text',...
'Tag','C12Sub',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'C12QD';

h91 = uicontrol(...
'Parent',h77,...
'Units','characters',...
'Position',[36.6 2.53846153846154 10.4 1.07692307692308],...
'String','0',...
'Style','text',...
'Tag','C12QD',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'C12SC';

h92 = uicontrol(...
'Parent',h77,...
'Units','characters',...
'Position',[36.6 1 10.4 1.07692307692308],...
'String','0',...
'Style','text',...
'Tag','C12SC',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text43';

h93 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'Position',[1.2 1.69230769230769 57.4 1.15384615384615],...
'String','Material Parameters: Vurgaftman, doi:10.1063/1.1368156',...
'Style','text',...
'Tag','text43',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text44';

h94 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'Position',[1.2 4.61538461538462 43.8 1.07692307692308],...
'String','CET: Ekins-Daukes, doi:10.1021/cg025502y',...
'Style','text',...
'Tag','text44',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text45';

h95 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'Position',[1.2 3.15384615384615 46.2 1.07692307692308],...
'String','mCET Cylinder: Bailey, doi:10.1063/1.3264967',...
'Style','text',...
'Tag','text45',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text46';

h96 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'Position',[61.2 2.61538461538462 40.4 1.07692307692308],...
'String','Created by: Steve Polly, RIT, 2014 v.1.0',...
'Style','text',...
'Tag','text46',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text47';

h97 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'Position',[73.2 1.46153846153846 16.4 1.07692307692308],...
'String','sjp5958@rit.edu',...
'Style','text',...
'Tag','text47',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text48';

h98 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'Position',[1.2 0.384615384615385 57.4 1.07692307692308],...
'String','Stiffness Calculator: Adachi, isbn: 9780470090329 pg. 49',...
'Style','text',...
'Tag','text48',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text80';

h99 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'Position',[62.6 0.384615384615385 37.8 1.07692307692308],...
'String','github.com/spolly/straincompensation',...
'Style','text',...
'Tag','text80',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );


hsingleton = h1;


% --- Set application data first then calling the CreateFcn. 
function local_CreateFcn(hObject, eventdata, createfcn, appdata)

if ~isempty(appdata)
   names = fieldnames(appdata);
   for i=1:length(names)
       name = char(names(i));
       setappdata(hObject, name, getfield(appdata,name));
   end
end

if ~isempty(createfcn)
   if isa(createfcn,'function_handle')
       createfcn(hObject, eventdata);
   else
       eval(createfcn);
   end
end


% --- Handles default GUIDE GUI creation and callback dispatch
function varargout = gui_mainfcn(gui_State, varargin)

gui_StateFields =  {'gui_Name'
    'gui_Singleton'
    'gui_OpeningFcn'
    'gui_OutputFcn'
    'gui_LayoutFcn'
    'gui_Callback'};
gui_Mfile = '';
for i=1:length(gui_StateFields)
    if ~isfield(gui_State, gui_StateFields{i})
        error(message('MATLAB:guide:StateFieldNotFound', gui_StateFields{ i }, gui_Mfile));
    elseif isequal(gui_StateFields{i}, 'gui_Name')
        gui_Mfile = [gui_State.(gui_StateFields{i}), '.m'];
    end
end

numargin = length(varargin);

if numargin == 0
    % STRAINCOMPENSATION
    % create the GUI only if we are not in the process of loading it
    % already
    gui_Create = true;
elseif local_isInvokeActiveXCallback(gui_State, varargin{:})
    % STRAINCOMPENSATION(ACTIVEX,...)
    vin{1} = gui_State.gui_Name;
    vin{2} = [get(varargin{1}.Peer, 'Tag'), '_', varargin{end}];
    vin{3} = varargin{1};
    vin{4} = varargin{end-1};
    vin{5} = guidata(varargin{1}.Peer);
    feval(vin{:});
    return;
elseif local_isInvokeHGCallback(gui_State, varargin{:})
    % STRAINCOMPENSATION('CALLBACK',hObject,eventData,handles,...)
    gui_Create = false;
else
    % STRAINCOMPENSATION(...)
    % create the GUI and hand varargin to the openingfcn
    gui_Create = true;
end

if ~gui_Create
    % In design time, we need to mark all components possibly created in
    % the coming callback evaluation as non-serializable. This way, they
    % will not be brought into GUIDE and not be saved in the figure file
    % when running/saving the GUI from GUIDE.
    designEval = false;
    if (numargin>1 && ishghandle(varargin{2}))
        fig = varargin{2};
        while ~isempty(fig) && ~ishghandle(fig,'figure')
            fig = get(fig,'parent');
        end
        
        designEval = isappdata(0,'CreatingGUIDEFigure') || isprop(fig,'__GUIDEFigure');
    end
        
    if designEval
        beforeChildren = findall(fig);
    end
    
    % evaluate the callback now
    varargin{1} = gui_State.gui_Callback;
    if nargout
        [varargout{1:nargout}] = feval(varargin{:});
    else       
        feval(varargin{:});
    end
    
    % Set serializable of objects created in the above callback to off in
    % design time. Need to check whether figure handle is still valid in
    % case the figure is deleted during the callback dispatching.
    if designEval && ishghandle(fig)
        set(setdiff(findall(fig),beforeChildren), 'Serializable','off');
    end
else
    if gui_State.gui_Singleton
        gui_SingletonOpt = 'reuse';
    else
        gui_SingletonOpt = 'new';
    end

    % Check user passing 'visible' P/V pair first so that its value can be
    % used by oepnfig to prevent flickering
    gui_Visible = 'auto';
    gui_VisibleInput = '';
    for index=1:2:length(varargin)
        if length(varargin) == index || ~ischar(varargin{index})
            break;
        end

        % Recognize 'visible' P/V pair
        len1 = min(length('visible'),length(varargin{index}));
        len2 = min(length('off'),length(varargin{index+1}));
        if ischar(varargin{index+1}) && strncmpi(varargin{index},'visible',len1) && len2 > 1
            if strncmpi(varargin{index+1},'off',len2)
                gui_Visible = 'invisible';
                gui_VisibleInput = 'off';
            elseif strncmpi(varargin{index+1},'on',len2)
                gui_Visible = 'visible';
                gui_VisibleInput = 'on';
            end
        end
    end
    
    % Open fig file with stored settings.  Note: This executes all component
    % specific CreateFunctions with an empty HANDLES structure.

    
    % Do feval on layout code in m-file if it exists
    gui_Exported = ~isempty(gui_State.gui_LayoutFcn);
    % this application data is used to indicate the running mode of a GUIDE
    % GUI to distinguish it from the design mode of the GUI in GUIDE. it is
    % only used by actxproxy at this time.   
    setappdata(0,genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name]),1);
    if gui_Exported
        gui_hFigure = feval(gui_State.gui_LayoutFcn, gui_SingletonOpt);

        % make figure invisible here so that the visibility of figure is
        % consistent in OpeningFcn in the exported GUI case
        if isempty(gui_VisibleInput)
            gui_VisibleInput = get(gui_hFigure,'Visible');
        end
        set(gui_hFigure,'Visible','off')

        % openfig (called by local_openfig below) does this for guis without
        % the LayoutFcn. Be sure to do it here so guis show up on screen.
        movegui(gui_hFigure,'onscreen');
    else
        gui_hFigure = local_openfig(gui_State.gui_Name, gui_SingletonOpt, gui_Visible);
        % If the figure has InGUIInitialization it was not completely created
        % on the last pass.  Delete this handle and try again.
        if isappdata(gui_hFigure, 'InGUIInitialization')
            delete(gui_hFigure);
            gui_hFigure = local_openfig(gui_State.gui_Name, gui_SingletonOpt, gui_Visible);
        end
    end
    if isappdata(0, genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name]))
        rmappdata(0,genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name]));
    end

    % Set flag to indicate starting GUI initialization
    setappdata(gui_hFigure,'InGUIInitialization',1);

    % Fetch GUIDE Application options
    gui_Options = getappdata(gui_hFigure,'GUIDEOptions');
    % Singleton setting in the GUI M-file takes priority if different
    gui_Options.singleton = gui_State.gui_Singleton;

    if ~isappdata(gui_hFigure,'GUIOnScreen')
        % Adjust background color
        if gui_Options.syscolorfig
            set(gui_hFigure,'Color', get(0,'DefaultUicontrolBackgroundColor'));
        end

        % Generate HANDLES structure and store with GUIDATA. If there is
        % user set GUI data already, keep that also.
        data = guidata(gui_hFigure);
        handles = guihandles(gui_hFigure);
        if ~isempty(handles)
            if isempty(data)
                data = handles;
            else
                names = fieldnames(handles);
                for k=1:length(names)
                    data.(char(names(k)))=handles.(char(names(k)));
                end
            end
        end
        guidata(gui_hFigure, data);
    end

    % Apply input P/V pairs other than 'visible'
    for index=1:2:length(varargin)
        if length(varargin) == index || ~ischar(varargin{index})
            break;
        end

        len1 = min(length('visible'),length(varargin{index}));
        if ~strncmpi(varargin{index},'visible',len1)
            try set(gui_hFigure, varargin{index}, varargin{index+1}), catch break, end
        end
    end

    % If handle visibility is set to 'callback', turn it on until finished
    % with OpeningFcn
    gui_HandleVisibility = get(gui_hFigure,'HandleVisibility');
    if strcmp(gui_HandleVisibility, 'callback')
        set(gui_hFigure,'HandleVisibility', 'on');
    end

    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure), varargin{:});

    if isscalar(gui_hFigure) && ishghandle(gui_hFigure)
        % Handle the default callbacks of predefined toolbar tools in this
        % GUI, if any
        guidemfile('restoreToolbarToolPredefinedCallback',gui_hFigure); 
        
        % Update handle visibility
        set(gui_hFigure,'HandleVisibility', gui_HandleVisibility);

        % Call openfig again to pick up the saved visibility or apply the
        % one passed in from the P/V pairs
        if ~gui_Exported
            gui_hFigure = local_openfig(gui_State.gui_Name, 'reuse',gui_Visible);
        elseif ~isempty(gui_VisibleInput)
            set(gui_hFigure,'Visible',gui_VisibleInput);
        end
        if strcmpi(get(gui_hFigure, 'Visible'), 'on')
            figure(gui_hFigure);
            
            if gui_Options.singleton
                setappdata(gui_hFigure,'GUIOnScreen', 1);
            end
        end

        % Done with GUI initialization
        if isappdata(gui_hFigure,'InGUIInitialization')
            rmappdata(gui_hFigure,'InGUIInitialization');
        end

        % If handle visibility is set to 'callback', turn it on until
        % finished with OutputFcn
        gui_HandleVisibility = get(gui_hFigure,'HandleVisibility');
        if strcmp(gui_HandleVisibility, 'callback')
            set(gui_hFigure,'HandleVisibility', 'on');
        end
        gui_Handles = guidata(gui_hFigure);
    else
        gui_Handles = [];
    end

    if nargout
        [varargout{1:nargout}] = feval(gui_State.gui_OutputFcn, gui_hFigure, [], gui_Handles);
    else
        feval(gui_State.gui_OutputFcn, gui_hFigure, [], gui_Handles);
    end

    if isscalar(gui_hFigure) && ishghandle(gui_hFigure)
        set(gui_hFigure,'HandleVisibility', gui_HandleVisibility);
    end
end

function gui_hFigure = local_openfig(name, singleton, visible)

% openfig with three arguments was new from R13. Try to call that first, if
% failed, try the old openfig.
if nargin('openfig') == 2
    % OPENFIG did not accept 3rd input argument until R13,
    % toggle default figure visible to prevent the figure
    % from showing up too soon.
    gui_OldDefaultVisible = get(0,'defaultFigureVisible');
    set(0,'defaultFigureVisible','off');
    gui_hFigure = openfig(name, singleton);
    set(0,'defaultFigureVisible',gui_OldDefaultVisible);
else
    gui_hFigure = openfig(name, singleton, visible);  
    %workaround for CreateFcn not called to create ActiveX
    if feature('HGUsingMATLABClasses')
        peers=findobj(findall(allchild(gui_hFigure)),'type','uicontrol','style','text');    
        for i=1:length(peers)
            if isappdata(peers(i),'Control')
                actxproxy(peers(i));
            end            
        end
    end
end

function result = local_isInvokeActiveXCallback(gui_State, varargin)

try
    result = ispc && iscom(varargin{1}) ...
             && isequal(varargin{1},gcbo);
catch
    result = false;
end

function result = local_isInvokeHGCallback(gui_State, varargin)

try
    fhandle = functions(gui_State.gui_Callback);
    result = ~isempty(findstr(gui_State.gui_Name,fhandle.file)) || ...
             (ischar(varargin{1}) ...
             && isequal(ishghandle(varargin{2}), 1) ...
             && (~isempty(strfind(varargin{1},[get(varargin{2}, 'Tag'), '_'])) || ...
                ~isempty(strfind(varargin{1}, '_CreateFcn'))) );
catch
    result = false;
end


