function varargout = straincompensation(varargin)
%SC_NEW_EXPORT M-file for straincompensation.fig
%      SC_NEW_EXPORT, by itself, creates a new SC_NEW_EXPORT or raises the existing
%      singleton*.
%
%      H = SC_NEW_EXPORT returns the handle to a new SC_NEW_EXPORT or the handle to
%      the existing singleton*.
%
%      SC_NEW_EXPORT('Property','Value',...) creates a new SC_NEW_EXPORT using the
%      given property value pairs. Unrecognized properties are passed via
%      varargin to straincompensation_OpeningFcn.  This calling syntax produces a
%      warning when there is an existing singleton*.
%
%      SC_NEW_EXPORT('CALLBACK') and SC_NEW_EXPORT('CALLBACK',hObject,...) call the
%      local function named CALLBACK in SC_NEW_EXPORT.M with the given input
%      arguments.
%
%      *See GUI Options on GUIDE's Tools menu.  Choose "GUI allows only one
%      instance to run (singleton)".
%
% See also: GUIDE, GUIDATA, GUIHANDLES

% Edit the above text to modify the response to help straincompensation

% Last Modified by GUIDE v2.5 18-Nov-2014 14:11:04

% Begin initialization code - DO NOT EDIT
gui_Singleton = 1;
gui_State = struct('gui_Name',       mfilename, ...
                   'gui_Singleton',  gui_Singleton, ...
                   'gui_OpeningFcn', @straincompensation_OpeningFcn, ...
                   'gui_OutputFcn',  @straincompensation_OutputFcn, ...
                   'gui_LayoutFcn',  @straincompensation_LayoutFcn, ...
                   'gui_Callback',   []);
if nargin && ischar(varargin{1})
   gui_State.gui_Callback = str2func(varargin{1});
end

if nargout
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
else
    gui_mainfcn(gui_State, varargin{:});
end
% End initialization code - DO NOT EDIT


% --- Executes just before straincompensation is made visible.
function straincompensation_OpeningFcn(hObject, eventdata, handles, varargin)
% This function has no output args, see OutputFcn.
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% varargin   unrecognized PropertyName/PropertyValue pairs from the
%            command line (see VARARGIN)

% Choose default command line output for straincompensation
handles.output = hObject;
%
handles.SubX=1;
handles.SubY=1;
handles.QDX=1;
handles.QDY=1;
handles.SCX=1;
handles.SCY=1;
set(handles.interpolate,'Value',1);

%These values also need to be changed in their respective GUI
%initializations. Search for '%@@@' to find instances
handles.SubIII = 'Ga';
handles.SubV = 'As';
handles.QDIII = 'In';
handles.QDV = 'As';
handles.SCIII = 'Ga';
handles.SCV = 'P';
handles.QDDiameter=25;
handles.QDHeight=2;
handles.QDDensity=5e10;
handles.WLThickness=1;
handles.interpolate=true;

% Update handles structure
guidata(hObject, handles);
%calculate_Callback(hObject, eventdata, handles)

% --- Outputs from this function are returned to the command line.
function varargout = straincompensation_OutputFcn(hObject, eventdata, handles)
% varargout  cell array for returning output args (see VARARGOUT);
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Get default command line output from handles structure
varargout{1} = handles.output;


% --- Executes on button press in calculate.
function calculate_Callback(hObject, eventdata, handles)
% hObject    handle to calculate (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

[subAC,subBC,subAD,subBD]=parseSelection(handles.SubIII, handles.SubV);
[aSub,c11iSub,c12iSub,c11aSub,c12aSub]=calcMaterial(subAC, subAD, handles.SubX, subBC, subBD, handles.SubY);

[qdAC,qdBC,qdAD,qdBD]=parseSelection(handles.QDIII, handles.QDV);
[aQD,c11iQD,c12iQD,c11aQD,c12aQD]=calcMaterial(qdAC, qdAD, handles.QDX, qdBC, qdBD, handles.QDY);

[scAC,scBC,scAD,scBD]=parseSelection(handles.SCIII, handles.SCV);
[aSC,c11iSC,c12iSC,c11aSC,c12aSC]=calcMaterial(scAC, scAD, handles.SCX, scBC, scBD, handles.SCY);


QDDensity=handles.QDDensity * 1e-16; %Angstrom^-2 {5e-6 A^-2 = 5e10 cm^-2}
QDDiameter=handles.QDDiameter * 10; %Angstrom
QDHeight=handles.QDHeight * 10; %Angstrom
WLThickness=handles.WLThickness * 10;

%Interpolated stiffness ratios
ASCi=c11iSC + c12iSC - (2*c12iSC.^2./c11iSC);
AQDi=c11iQD + c12iQD - (2*c12iQD.^2./c11iQD);

%Adachi equation stiffness ratios
ASCa=c11aSC + c12aSC - (2*c12aSC.^2./c11aSC);
AQDa=c11aQD + c12aQD - (2*c12aQD.^2./c11aQD);

%QD Volume Calculations
    %QD as spherical cap
    vQDSphCap=pi.*QDHeight./6 .* (3 .*(QDDiameter/2).^2 + QDHeight.^2);

    %QD as cylinder
    QDsigma=(QDDiameter/2)^2*pi; %QD base area
    vQDCyl=QDHeight*QDsigma;

    %QD as oblate hemispheroid
    vQDOblSph=((4/3)*pi*(QDDiameter/2)^2*QDHeight)/2;

%Strain Compensation Calculations
    %CET QD Thickness
    CETQDi=QDHeight*((AQDi .* aSC^2 .* (aSub - aQD))./(ASCi .* aQD^2 .* (aSC - aSub)))/10;
    CETQDa=QDHeight*((AQDa .* aSC^2 .* (aSub - aQD))./(ASCa .* aQD^2 .* (aSC - aSub)))/10;

    %CET WL Thickness
    CETWLi=WLThickness*((AQDi .* aSC^2 .* (aSub - aQD))./(ASCi .* aQD^2 .* (aSC - aSub)))/10;
    CETWLa=WLThickness*((AQDa .* aSC^2 .* (aSub - aQD))./(ASCa .* aQD^2 .* (aSC - aSub)))/10;

    %Effective coverage of QD material (Cylinder)
    tQDWLCyl=(QDsigma*QDDensity)*QDHeight+(1-QDsigma*QDDensity)*WLThickness;

    %mCET Cylinder
    mCETcyli=(QDsigma*QDDensity)*CETQDi + (1-QDsigma*QDDensity)*CETWLi; %weighted SC thickness
    mCETcyla=(QDsigma*QDDensity)*CETQDa + (1-QDsigma*QDDensity)*CETWLa; %weighted SC thickness

    %Effective coverage of QD material (Oblate Hemispheroid)
    tQD=vQDOblSph*QDDensity; %volume of QD times QD density gives average thickness of QD per area
    tQDWL=WLThickness+tQD; %WL is treated as external to QD

    %mCET Oblate Hemispheroid
    mCETsphi=tQDWL*((AQDi .* aSC^2 .* (aSub - aQD))./(ASCi .* aQD^2 .* (aSC - aSub)))/10;
    mCETspha=tQDWL*((AQDa .* aSC^2 .* (aSub - aQD))./(ASCa .* aQD^2 .* (aSC - aSub)))/10;


set(handles.QDVolSphCap,'String',num2str(vQDSphCap/1000,4)) %convert to nm^3 from A^3
set(handles.QDVolCyl,'String',num2str(vQDCyl/1000,4)) %convert to nm^3 from A^3
set(handles.QDVolOblSph,'String',num2str(vQDOblSph/1000,4)) %convert to nm^3 from A^3

set(handles.QDCoverageQW,'String',num2str(QDHeight/10,4)) %convert to nm^3 cm^-2 from A^3 cm^-2
set(handles.QDCoverageCyl,'String',num2str(tQDWLCyl/10,4))
set(handles.QDCoverageOblSph,'String',num2str(tQDWL/10,4))

set(handles.aSub,'String',num2str(aSub))
set(handles.aQD,'String',num2str(aQD))
set(handles.aSC,'String',num2str(aSC))

if handles.interpolate
    set(handles.CET,'String',num2str(CETQDi,4))
    set(handles.MCETCyl,'String',num2str(mCETcyli,4))
    set(handles.MCETSphere,'String',num2str(mCETsphi,4))

    set(handles.C11Sub,'String',num2str(c11iSub,4))
    set(handles.C11QD,'String',num2str(c11iQD,4))
    set(handles.C11SC,'String',num2str(c11iSC,4))

    set(handles.C12Sub,'String',num2str(c12iSub,4))
    set(handles.C12QD,'String',num2str(c12iQD,4))
    set(handles.C12SC,'String',num2str(c12iSC,4))
else
    set(handles.CET,'String',num2str(CETQDa,4))
    set(handles.MCETCyl,'String',num2str(mCETcyla,4))
    set(handles.MCETSphere,'String',num2str(mCETspha,4))

    set(handles.C11Sub,'String',num2str(c11aSub,4))
    set(handles.C11QD,'String',num2str(c11aQD,4))
    set(handles.C11SC,'String',num2str(c11aSC,4))

    set(handles.C12Sub,'String',num2str(c12aSub,4))
    set(handles.C12QD,'String',num2str(c12aQD,4))
    set(handles.C12SC,'String',num2str(c12aSC,4))
end

guidata(hObject,handles)

function QDDiameter_Callback(hObject, eventdata, handles)
% hObject    handle to QDDiameter (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
handles.QDDiameter=str2double(get(hObject,'String'));
guidata(hObject,handles)

% --- Executes during object creation, after setting all properties.
function QDDiameter_CreateFcn(hObject, eventdata, handles)
% hObject    handle to QDDiameter (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

function QDHeight_Callback(hObject, eventdata, handles)
% hObject    handle to QDHeight (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
handles.QDHeight=str2double(get(hObject,'String'));
guidata(hObject,handles)

% --- Executes during object creation, after setting all properties.
function QDHeight_CreateFcn(hObject, eventdata, handles)
% hObject    handle to QDHeight (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function QDDensity_Callback(hObject, eventdata, handles)
% hObject    handle to QDDensity (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
handles.QDDensity=str2double(get(hObject,'String'));
guidata(hObject,handles)

% --- Executes during object creation, after setting all properties.
function QDDensity_CreateFcn(hObject, eventdata, handles)
% hObject    handle to QDDensity (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function WLThickness_Callback(hObject, eventdata, handles)
% hObject    handle to WLThickness (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
handles.WLThickness=str2double(get(hObject,'String'));
guidata(hObject,handles)

% --- Executes during object creation, after setting all properties.
function WLThickness_CreateFcn(hObject, eventdata, handles)
% hObject    handle to WLThickness (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

% --- Executes on selection change in SubIII.
function SubIII_Callback(hObject, eventdata, handles)
% hObject    handle to SubIII (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
contents = cellstr(get(hObject,'String'));
selected = contents{get(hObject,'Value')};
switch selected;
case 'Al'
	handles.SubIII = 'Al';
case 'Ga'
	handles.SubIII = 'Ga';
case 'In'
	handles.SubIII = 'In';
case 'Al_(x)Ga_(1-x)'
	handles.SubIII = 'Al_(x)Ga_(1-x)';
case 'Al_(x)In_(1-x)'
	handles.SubIII = 'Al_(x)In_(1-x)';
case 'In_(x)Ga_(1-x)'
	handles.SubIII = 'In_(x)Ga_(1-x)';
end
guidata(hObject,handles)

% --- Executes during object creation, after setting all properties.
function SubIII_CreateFcn(hObject, eventdata, handles)
% hObject    handle to SubIII (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

% --- Executes on selection change in SubV.
function SubV_Callback(hObject, eventdata, handles)
% hObject    handle to SubV (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
contents = cellstr(get(hObject,'String'));
selected = contents{get(hObject,'Value')};
switch selected;
case 'P'
	handles.SubV = 'P';
case 'As'
	handles.SubV = 'As';
case 'Sb'
	handles.SubV = 'In';
case 'As_(y)P_(1-y)'
	handles.SubV = 'As_(y)P_(1-y)';
case 'As_(y)Sb_(1-y)'
	handles.SubV = 'As_(y)Sb_(1-y)';
case 'Sb_(y)P_(1-y)'
	handles.SubV = 'Sb_(y)P_(1-y)';
end
guidata(hObject,handles)

% --- Executes during object creation, after setting all properties.
function SubV_CreateFcn(hObject, eventdata, handles)
% hObject    handle to SubV (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

% --- Executes on selection change in QDIII.
function QDIII_Callback(hObject, eventdata, handles)
% hObject    handle to QDIII (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
contents = cellstr(get(hObject,'String'));
selected = contents{get(hObject,'Value')};
switch selected;
case 'Al'
	handles.QDIII = 'Al';
case 'Ga'
	handles.QDIII = 'Ga';
case 'In'
	handles.QDIII = 'In';
case 'Al_(x)Ga_(1-x)'
	handles.QDIII = 'Al_(x)Ga_(1-x)';
case 'Al_(x)In_(1-x)'
	handles.QDIII = 'Al_(x)In_(1-x)';
case 'In_(x)Ga_(1-x)'
	handles.QDIII = 'In_(x)Ga_(1-x)';
end
guidata(hObject,handles)

% --- Executes during object creation, after setting all properties.
function QDIII_CreateFcn(hObject, eventdata, handles)
% hObject    handle to QDIII (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

% --- Executes on selection change in QDV.
function QDV_Callback(hObject, eventdata, handles)
% hObject    handle to QDV (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
contents = cellstr(get(hObject,'String'));
selected = contents{get(hObject,'Value')};
switch selected;
case 'P'
	handles.QDV = 'P';
case 'As'
	handles.QdV = 'As';
case 'Sb'
	handles.QDV = 'Sb';
case 'As_(y)P_(1-y)'
	handles.QDV = 'As_(y)P_(1-y)';
case 'As_(y)Sb_(1-y)'
	handles.QDV = 'As_(y)Sb_(1-y)';
case 'Sb_(y)P_(1-y)'
	handles.QdV = 'Sb_(y)P_(1-y)';
end
guidata(hObject,handles)

% --- Executes during object creation, after setting all properties.
function QDV_CreateFcn(hObject, eventdata, handles)
% hObject    handle to QDV (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

% --- Executes on selection change in SCIII.
function SCIII_Callback(hObject, eventdata, handles)
% hObject    handle to SCIII (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
contents = cellstr(get(hObject,'String'));
selected = contents{get(hObject,'Value')};
switch selected;
case 'Al'
	handles.SCIII = 'Al';
case 'Ga'
	handles.SCIII = 'Ga';
case 'In'
	handles.SCIII = 'In';
case 'Al_(x)Ga_(1-x)'
	handles.SCIII = 'Al_(x)Ga_(1-x)';
case 'Al_(x)In_(1-x)'
	handles.SCIII = 'Al_(x)In_(1-x)';
case 'In_(x)Ga_(1-x)'
	handles.SCIII = 'In_(x)Ga_(1-x)';
end
guidata(hObject,handles)

% --- Executes during object creation, after setting all properties.
function SCIII_CreateFcn(hObject, eventdata, handles)
% hObject    handle to SCIII (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

% --- Executes on selection change in SCV.
function SCV_Callback(hObject, eventdata, handles)
% hObject    handle to SCV (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
contents = cellstr(get(hObject,'String'));
selected = contents{get(hObject,'Value')};
switch selected;
case 'P'
	handles.SCV = 'P';
case 'As'
	handles.SCV = 'As';
case 'Sb'
	handles.SCV = 'In';
case 'As_(y)P_(1-y)'
	handles.SCV = 'As_(y)P_(1-y)';
case 'As_(y)Sb_(1-y)'
	handles.SCV = 'As_(y)Sb_(1-y)';
case 'Sb_(y)P_(1-y)'
	handles.SCV = 'Sb_(y)P_(1-y)';
end
guidata(hObject,handles)

% --- Executes during object creation, after setting all properties.
function SCV_CreateFcn(hObject, eventdata, handles)
% hObject    handle to SCV (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

function SubX_Callback(hObject, eventdata, handles)
% hObject    handle to SubX (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
handles.SubX=str2double(get(hObject,'String'));
guidata(hObject,handles)

% --- Executes during object creation, after setting all properties.
function SubX_CreateFcn(hObject, eventdata, handles)
% hObject    handle to SubX (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

function SubY_Callback(hObject, eventdata, handles)
% hObject    handle to SubY (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
handles.SubY=str2double(get(hObject,'String'));
guidata(hObject,handles)

% --- Executes during object creation, after setting all properties.
function SubY_CreateFcn(hObject, eventdata, handles)
% hObject    handle to SubY (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

function QDX_Callback(hObject, eventdata, handles)
% hObject    handle to QDX (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
handles.QDX=str2double(get(hObject,'String'));
guidata(hObject,handles)


% --- Executes during object creation, after setting all properties.
function QDX_CreateFcn(hObject, eventdata, handles)
% hObject    handle to QDX (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

function QDY_Callback(hObject, eventdata, handles)
% hObject    handle to QDY (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
handles.QDY=str2double(get(hObject,'String'));
guidata(hObject,handles)


% --- Executes during object creation, after setting all properties.
function QDY_CreateFcn(hObject, eventdata, handles)
% hObject    handle to QDY (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

function SCX_Callback(hObject, eventdata, handles)
% hObject    handle to SCX (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
handles.SCX=str2double(get(hObject,'String'));
guidata(hObject,handles)

% --- Executes during object creation, after setting all properties.
function SCX_CreateFcn(hObject, eventdata, handles)
% hObject    handle to SCX (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

function SCY_Callback(hObject, eventdata, handles)
% hObject    handle to SCY (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
handles.SCY=str2double(get(hObject,'String'));
guidata(hObject,handles)

% --- Executes during object creation, after setting all properties.
function SCY_CreateFcn(hObject, eventdata, handles)
% hObject    handle to SCY (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

% --- Executes on button press in interpolate.
function interpolate_Callback(hObject, eventdata, handles)
% hObject    handle to interpolate (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
if (get(hObject,'Value') == get(hObject,'Max'))
	handles.interpolate=true;
else
	handles.interpolate=false;
end
guidata(hObject,handles)
calculate_Callback(hObject, eventdata, handles)


% --- Creates and returns a handle to the GUI figure.
function h1 = straincompensation_LayoutFcn(policy)
% policy - create a new figure or use a singleton. 'new' or 'reuse'.

persistent hsingleton;
if strcmpi(policy, 'reuse') & ishandle(hsingleton)
    h1 = hsingleton;
    return;
end

appdata = [];
appdata.GUIDEOptions = struct(...
    'active_h', [], ...
    'taginfo', struct(...
    'figure', 2, ...
    'uipanel', 6, ...
    'popupmenu', 14, ...
    'text', 82, ...
    'edit', 12, ...
    'pushbutton', 2, ...
    'slider', 2, ...
    'radiobutton', 2, ...
    'checkbox', 2), ...
    'override', 1, ...
    'release', 13, ...
    'resize', 'none', ...
    'accessibility', 'callback', ...
    'mfile', 1, ...
    'callbacks', 1, ...
    'singleton', 1, ...
    'syscolorfig', 1, ...
    'blocking', 0, ...
    'lastFilename', 'C:\Users\sjp5958\Documents\MATLAB\sc_new.fig', ...
    'lastSavedFile', 'C:\Users\sjp5958\Documents\MATLAB\straincompensation.m');
appdata.lastValidTag = 'figure1';
appdata.GUIDELayoutEditor = [];
appdata.initTags = struct(...
    'handle', [], ...
    'tag', 'figure1');

h1 = figure(...
'Units','characters',...
'Color',[0.941176470588235 0.941176470588235 0.941176470588235],...
'Colormap',[0 0 0.5625;0 0 0.625;0 0 0.6875;0 0 0.75;0 0 0.8125;0 0 0.875;0 0 0.9375;0 0 1;0 0.0625 1;0 0.125 1;0 0.1875 1;0 0.25 1;0 0.3125 1;0 0.375 1;0 0.4375 1;0 0.5 1;0 0.5625 1;0 0.625 1;0 0.6875 1;0 0.75 1;0 0.8125 1;0 0.875 1;0 0.9375 1;0 1 1;0.0625 1 1;0.125 1 0.9375;0.1875 1 0.875;0.25 1 0.8125;0.3125 1 0.75;0.375 1 0.6875;0.4375 1 0.625;0.5 1 0.5625;0.5625 1 0.5;0.625 1 0.4375;0.6875 1 0.375;0.75 1 0.3125;0.8125 1 0.25;0.875 1 0.1875;0.9375 1 0.125;1 1 0.0625;1 1 0;1 0.9375 0;1 0.875 0;1 0.8125 0;1 0.75 0;1 0.6875 0;1 0.625 0;1 0.5625 0;1 0.5 0;1 0.4375 0;1 0.375 0;1 0.3125 0;1 0.25 0;1 0.1875 0;1 0.125 0;1 0.0625 0;1 0 0;0.9375 0 0;0.875 0 0;0.8125 0 0;0.75 0 0;0.6875 0 0;0.625 0 0;0.5625 0 0],...
'IntegerHandle','off',...
'InvertHardcopy',get(0,'defaultfigureInvertHardcopy'),...
'MenuBar','none',...
'Name','sc',...
'NumberTitle','off',...
'PaperPosition',get(0,'defaultfigurePaperPosition'),...
'Position',[103.8 26.7692307692308 104 34.8461538461538],...
'Resize','off',...
'HandleVisibility','callback',...
'UserData',[],...
'Tag','figure1',...
'Visible','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'uipanel1';

h2 = uipanel(...
'Parent',h1,...
'Units','characters',...
'Title','Material Systems',...
'Clipping','on',...
'Position',[1.6 13.9230769230769 51.6 20.1538461538462],...
'Tag','uipanel1',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'SubIII';

h3 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)straincompensation('SubIII_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[7 14.6923076923077 21 1.92307692307692],...
'String',{  'Al'; 'Ga'; 'In'; 'Al_(x)Ga_(1-x)'; 'Al_(x)In_(1-x)'; 'In_(x)Ga_(1-x)' },...
'Style','popupmenu',...
'Value',2,...%@@@
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)straincompensation('SubIII_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','SubIII');

appdata = [];
appdata.lastValidTag = 'SubV';

h4 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)straincompensation('SubV_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[28.4 14.6923076923077 21.6 1.92307692307692],...
'String',{  'P'; 'As'; 'Sb'; 'As_(y)P_(1-y)'; 'As_(y)Sb_(1-y)'; 'Sb_(y)P_(1-y)' },...
'Style','popupmenu',...
'Value',2,...%@@@
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)straincompensation('SubV_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','SubV');

appdata = [];
appdata.lastValidTag = 'text1';

h5 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'Position',[6.2 16.6153846153846 10.4 1.07692307692308],...
'String','Substrate',...
'Style','text',...
'Tag','text1',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'QDIII';

h6 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)straincompensation('QDIII_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[7 9 21 1.92307692307692],...
'String',{  'Al'; 'Ga'; 'In'; 'Al_(x)Ga_(1-x)'; 'Al_(x)In_(1-x)'; 'In_(x)Ga_(1-x)' },...
'Style','popupmenu',...
'Value',3,...%@@@
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)straincompensation('QDIII_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','QDIII');

appdata = [];
appdata.lastValidTag = 'QDV';

h7 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)straincompensation('QDV_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[28.4 9 21.6 1.92307692307692],...
'String',{  'P'; 'As'; 'Sb'; 'As_(y)P_(1-y)'; 'As_(y)Sb_(1-y)'; 'Sb_(y)P_(1-y)' },...
'Style','popupmenu',...
'Value',2,...%@@@
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)straincompensation('QDV_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','QDV');

appdata = [];
appdata.lastValidTag = 'SCIII';

h8 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)straincompensation('SCIII_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[7 3.23076923076923 21 1.92307692307692],...
'String',{  'Al'; 'Ga'; 'In'; 'Al_(x)Ga_(1-x)'; 'Al_(x)In_(1-x)'; 'In_(x)Ga_(1-x)' },...
'Style','popupmenu',...
'Value',2,...%@@@
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)straincompensation('SCIII_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','SCIII');

appdata = [];
appdata.lastValidTag = 'SCV';

h9 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)straincompensation('SCV_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[28.4 3.23076923076923 21.6 1.92307692307692],...
'String',{  'P'; 'As'; 'Sb'; 'As_(y)P_(1-y)'; 'As_(y)Sb_(1-y)'; 'Sb_(y)P_(1-y)' },...
'Style','popupmenu',...
'Value',1,...%@@@
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)straincompensation('SCV_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','SCV');

appdata = [];
appdata.lastValidTag = 'text2';

h10 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'Position',[6.2 11.0769230769231 13 1.07692307692308],...
'String','Quantum Dot',...
'Style','text',...
'Tag','text2',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text3';

h11 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'Position',[6.2 5.15384615384615 20.6 1.07692307692308],...
'String','Strain Compensation',...
'Style','text',...
'Tag','text3',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'SubX';

h12 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)straincompensation('SubX_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[10.4 13 5.8 1.76923076923077],...
'String','1',...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)straincompensation('SubX_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','SubX');

appdata = [];
appdata.lastValidTag = 'text4';

h13 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'Position',[7 13.1538461538462 3.2 1.46153846153846],...
'String','x:',...
'Style','text',...
'Tag','text4',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'SubY';

h14 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)straincompensation('SubY_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[30.2 13 6 1.76923076923077],...
'String','1',...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)straincompensation('SubY_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','SubY');

appdata = [];
appdata.lastValidTag = 'text5';

h15 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'Position',[26.8 13.1538461538462 3.2 1.46153846153846],...
'String','y:',...
'Style','text',...
'Tag','text5',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'QDX';

h16 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)straincompensation('QDX_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[10.6 7.23076923076923 5.6 1.76923076923077],...
'String','1',...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)straincompensation('QDX_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','QDX');

appdata = [];
appdata.lastValidTag = 'text6';

h17 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'Position',[7.2 7.38461538461539 3.2 1.46153846153846],...
'String','x:',...
'Style','text',...
'Tag','text6',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'QDY';

h18 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)straincompensation('QDY_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[30.2 7.23076923076923 6 1.76923076923077],...
'String','1',...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)straincompensation('QDY_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','QDY');

appdata = [];
appdata.lastValidTag = 'text7';

h19 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'Position',[26.8 7.38461538461539 3.2 1.46153846153846],...
'String','y:',...
'Style','text',...
'Tag','text7',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'SCX';

h20 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)straincompensation('SCX_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[10.4 1.38461538461538 5.8 1.76923076923077],...
'String','1',...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)straincompensation('SCX_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','SCX');

appdata = [];
appdata.lastValidTag = 'text8';

h21 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'Position',[7 1.53846153846154 3.2 1.46153846153846],...
'String','x:',...
'Style','text',...
'Tag','text8',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'SCY';

h22 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)straincompensation('SCY_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[30.2 1.38461538461538 6 1.76923076923077],...
'String','1',...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)straincompensation('SCY_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','SCY');

appdata = [];
appdata.lastValidTag = 'text9';

h23 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'Position',[26.8 1.53846153846154 3.2 1.46153846153846],...
'String','y:',...
'Style','text',...
'Tag','text9',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'interpolate';

h24 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'Callback',@(hObject,eventdata)straincompensation('interpolate_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[22.2 17.3076923076923 25.8 1.76923076923077],...
'String','Interpolate Stiffness',...
'Style','checkbox',...
'Tag','interpolate',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'uipanel2';

h25 = uipanel(...
'Parent',h1,...
'Units','characters',...
'Title','QD Properties',...
'Clipping','on',...
'Position',[53.8 19.9230769230769 50.4 14.1538461538462],...
'Tag','uipanel2',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text10';

h26 = uicontrol(...
'Parent',h25,...
'Units','characters',...
'Position',[3.4 11.3076923076923 13.4 1.07692307692308],...
'String','QD Diameter:',...
'Style','text',...
'Tag','text10',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text11';

h27 = uicontrol(...
'Parent',h25,...
'Units','characters',...
'Position',[6.4 9.69230769230771 10.4 1.07692307692308],...
'String','QD Height:',...
'Style','text',...
'Tag','text11',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text12';

h28 = uicontrol(...
'Parent',h25,...
'Units','characters',...
'Position',[4 8.07692307692308 12.8 1.07692307692308],...
'String','QD Density:',...
'Style','text',...
'Tag','text12',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text13';

h29 = uicontrol(...
'Parent',h25,...
'Units','characters',...
'Position',[1.8 6.46153846153846 15 1.07692307692308],...
'String','WL Thickness:',...
'Style','text',...
'Tag','text13',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'QDDiameter';

h30 = uicontrol(...
'Parent',h25,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)straincompensation('QDDiameter_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[17.2 11.1538461538462 12.4 1.30769230769231],...
'String','25',...%@@@
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)straincompensation('QDDiameter_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','QDDiameter');

appdata = [];
appdata.lastValidTag = 'QDHeight';

h31 = uicontrol(...
'Parent',h25,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)straincompensation('QDHeight_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[17.2 9.53846153846155 12.4 1.30769230769231],...
'String','2',...%@@@
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)straincompensation('QDHeight_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','QDHeight');

appdata = [];
appdata.lastValidTag = 'QDDensity';

h32 = uicontrol(...
'Parent',h25,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)straincompensation('QDDensity_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[17.2 7.92307692307693 12.4 1.30769230769231],...
'String','5e10',...%@@@
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)straincompensation('QDDensity_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','QDDensity');

appdata = [];
appdata.lastValidTag = 'WLThickness';

h33 = uicontrol(...
'Parent',h25,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)straincompensation('WLThickness_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[17.2 6.3076923076923 12.4 1.30769230769231],...
'String','1',...%@@@
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)straincompensation('WLThickness_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','WLThickness');

appdata = [];
appdata.lastValidTag = 'text14';

h34 = uicontrol(...
'Parent',h25,...
'Units','characters',...
'Position',[30 11.3076923076923 5.8 1.07692307692308],...
'String','[nm]',...
'Style','text',...
'Tag','text14',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text15';

h35 = uicontrol(...
'Parent',h25,...
'Units','characters',...
'Position',[30 9.69230769230771 5.8 1.07692307692308],...
'String','[nm]',...
'Style','text',...
'Tag','text15',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text16';

h36 = uicontrol(...
'Parent',h25,...
'Units','characters',...
'Position',[30 8.07692307692308 8.8 1.07692307692308],...
'String','[cm^-2]',...
'Style','text',...
'Tag','text16',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text17';

h37 = uicontrol(...
'Parent',h25,...
'Units','characters',...
'Position',[30 6.46153846153846 5.8 1.07692307692308],...
'String','[nm]',...
'Style','text',...
'Tag','text17',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text55';

h38 = uicontrol(...
'Parent',h25,...
'Units','characters',...
'Position',[1.8 4.15384615384615 19.2 1.07692307692308],...
'String','QD Vol (Sph. Cap):',...
'Style','text',...
'Tag','text55',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text56';

h39 = uicontrol(...
'Parent',h25,...
'Units','characters',...
'Position',[34.6000000000001 4.15384615384615 6.4 1.07692307692308],...
'String','[nm^3]',...
'Style','text',...
'Tag','text56',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'QDVolSphCap';

h40 = uicontrol(...
'Parent',h25,...
'Units','characters',...
'Position',[21.6 4 11.8 1.23076923076923],...
'String','0',...
'Style','text',...
'Tag','QDVolSphCap',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text58';

h41 = uicontrol(...
'Parent',h25,...
'Units','characters',...
'Position',[1.8 2.76923076923077 19.2 1.07692307692308],...
'String','QD Vol (Cylinder):',...
'Style','text',...
'Tag','text58',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text59';

h42 = uicontrol(...
'Parent',h25,...
'Units','characters',...
'Position',[34.6000000000001 2.76923076923077 6.4 1.07692307692308],...
'String','[nm^3]',...
'Style','text',...
'Tag','text59',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'QDVolCyl';

h43 = uicontrol(...
'Parent',h25,...
'Units','characters',...
'Position',[21.6 2.61538461538462 11.8 1.23076923076923],...
'String','0',...
'Style','text',...
'Tag','QDVolCyl',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text61';

h44 = uicontrol(...
'Parent',h25,...
'Units','characters',...
'Position',[1.8 1.38461538461538 19.2 1.07692307692308],...
'String','QD Vol (Obl. Sph.):',...
'Style','text',...
'Tag','text61',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text62';

h45 = uicontrol(...
'Parent',h25,...
'Units','characters',...
'Position',[34.6 1.38461538461538 6.4 1.07692307692308],...
'String','[nm^3]',...
'Style','text',...
'Tag','text62',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'QDVolOblSph';

h46 = uicontrol(...
'Parent',h25,...
'Units','characters',...
'Position',[21.6 1.23076923076923 11.8 1.23076923076923],...
'String','0',...
'Style','text',...
'Tag','QDVolOblSph',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'uipanel3';

h47 = uipanel(...
'Parent',h1,...
'Units','characters',...
'Title','Strain Compensation',...
'Clipping','on',...
'Position',[54.2 3.92307692307692 50 15.6923076923077],...
'Tag','uipanel3',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text18';

h48 = uicontrol(...
'Parent',h47,...
'Units','characters',...
'Position',[2.6 9.76923076923077 23.8 1.15384615384615],...
'String','CET (QD Height as QW)',...
'Style','text',...
'Tag','text18',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'CET';

h49 = uicontrol(...
'Parent',h47,...
'Units','characters',...
'Position',[5.2 8.61538461538462 17 1.15384615384615],...
'String','0',...
'Style','text',...
'Tag','CET',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text20';

h50 = uicontrol(...
'Parent',h47,...
'Units','characters',...
'Position',[22.6 8.69230769230769 5.8 1.07692307692308],...
'String','[nm]',...
'Style','text',...
'Tag','text20',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text21';

h51 = uicontrol(...
'Parent',h47,...
'Units','characters',...
'Position',[2.4 6.23076923076923 30.4 1.07692307692308],...
'String','Modified CET (QD as Cylinder)',...
'Style','text',...
'Tag','text21',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'MCETCyl';

h52 = uicontrol(...
'Parent',h47,...
'Units','characters',...
'Position',[3.6 5.07692307692308 20 1.15384615384615],...
'String','0',...
'Style','text',...
'Tag','MCETCyl',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text24';

h53 = uicontrol(...
'Parent',h47,...
'Units','characters',...
'Position',[22.6 5.30769230769231 5.8 1.07692307692308],...
'String','[nm]',...
'Style','text',...
'Tag','text24',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text25';

h54 = uicontrol(...
'Parent',h47,...
'Units','characters',...
'Position',[2.2 2.84615384615385 43.2 1.07692307692308],...
'String','Modified CET (QD as Oblate-Hemispheroid)',...
'Style','text',...
'Tag','text25',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'MCETSphere';

h55 = uicontrol(...
'Parent',h47,...
'Units','characters',...
'Position',[5.4 1.69230769230769 17 1.15384615384615],...
'String','0',...
'Style','text',...
'Tag','MCETSphere',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text27';

h56 = uicontrol(...
'Parent',h47,...
'Units','characters',...
'Position',[22.6 1.76923076923077 5.8 1.07692307692308],...
'String','[nm]',...
'Style','text',...
'Tag','text27',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'calculate';

h57 = uicontrol(...
'Parent',h47,...
'Units','characters',...
'Callback',@(hObject,eventdata)straincompensation('calculate_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[33.2 12.3846153846154 14.6 1.76923076923077],...
'String','Calculate',...
'Tag','calculate',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text72';

h58 = uicontrol(...
'Parent',h47,...
'Units','characters',...
'Position',[23.2 0.615384615384615 20.6 1.07692307692308],...
'String','[nm^3 cm^-2] or [nm]',...
'Style','text',...
'Tag','text72',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text73';

h59 = uicontrol(...
'Parent',h47,...
'Units','characters',...
'Position',[5.8 10.8461538461538 29.6 1.46153846153846],...
'String','Effective QD + WL Thickness',...
'Style','text',...
'Tag','text73',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text74';

h60 = uicontrol(...
'Parent',h47,...
'Units','characters',...
'Position',[5.8 12.0769230769231 23.8 1.46153846153846],...
'String','Required SC Thickness',...
'Style','text',...
'Tag','text74',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'QDCoverageOblSph';

h61 = uicontrol(...
'Parent',h47,...
'Units','characters',...
'Position',[5.4 0.538461538461539 17 1.15384615384615],...
'String','0',...
'Style','text',...
'Tag','QDCoverageOblSph',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text76';

h62 = uicontrol(...
'Parent',h47,...
'Units','characters',...
'Position',[23.2 4.15384615384615 20.6 1.07692307692308],...
'String','[nm^3 cm^-2] or [nm]',...
'Style','text',...
'Tag','text76',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'QDCoverageCyl';

h63 = uicontrol(...
'Parent',h47,...
'Units','characters',...
'Position',[3.6 3.84615384615385 20 1.15384615384615],...
'String','0',...
'Style','text',...
'Tag','QDCoverageCyl',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'QDCoverageQW';

h64 = uicontrol(...
'Parent',h47,...
'Units','characters',...
'Position',[5.2 7.46153846153847 17 1.15384615384615],...
'String','0',...
'Style','text',...
'Tag','QDCoverageQW',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text79';

h65 = uicontrol(...
'Parent',h47,...
'Units','characters',...
'Position',[23.2 7.53846153846154 20.6 1.07692307692308],...
'String','[nm^3 cm^-2] or [nm]',...
'Style','text',...
'Tag','text79',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'uipanel4';

h66 = uipanel(...
'Parent',h1,...
'Units','characters',...
'Title','Literature or Calculated Values',...
'Clipping','on',...
'Position',[1.6 5.76923076923077 51.4 8],...
'Tag','uipanel4',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text28';

h67 = uicontrol(...
'Parent',h66,...
'Units','characters',...
'Position',[1.2 4.15384615384615 5 1.15384615384615],...
'String','Sub',...
'Style','text',...
'Tag','text28',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text29';

h68 = uicontrol(...
'Parent',h66,...
'Units','characters',...
'Position',[1.6 2.69230769230769 4.6 1.07692307692308],...
'String','QD',...
'Style','text',...
'Tag','text29',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text30';

h69 = uicontrol(...
'Parent',h66,...
'Units','characters',...
'Position',[1 1.15384615384615 5.2 1.07692307692308],...
'String','SC',...
'Style','text',...
'Tag','text30',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text31';

h70 = uicontrol(...
'Parent',h66,...
'Units','characters',...
'Position',[7.2 5.61538461538462 13 1.07692307692308],...
'String','a [Angstrom]',...
'Style','text',...
'Tag','text31',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text32';

h71 = uicontrol(...
'Parent',h66,...
'Units','characters',...
'Position',[20.2 5.61538461538462 15.6 1.07692307692308],...
'String','C11 [GPa]',...
'Style','text',...
'Tag','text32',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text33';

h72 = uicontrol(...
'Parent',h66,...
'Units','characters',...
'Position',[35.4 5.61538461538462 14.2 1.07692307692308],...
'String','C12 [GPa]',...
'Style','text',...
'Tag','text33',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'aSub';

h73 = uicontrol(...
'Parent',h66,...
'Units','characters',...
'Position',[8.40000000000001 4.07692307692308 10.4 1.07692307692308],...
'String','0',...
'Style','text',...
'Tag','aSub',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'aQD';

h74 = uicontrol(...
'Parent',h66,...
'Units','characters',...
'Position',[8.40000000000001 2.53846153846154 10.4 1.07692307692308],...
'String','0',...
'Style','text',...
'Tag','aQD',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'aSC';

h75 = uicontrol(...
'Parent',h66,...
'Units','characters',...
'Position',[8.40000000000001 1 10.4 1.07692307692308],...
'String','0',...
'Style','text',...
'Tag','aSC',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'C11Sub';

h76 = uicontrol(...
'Parent',h66,...
'Units','characters',...
'Position',[22 4.07692307692308 10.4 1.07692307692308],...
'String','0',...
'Style','text',...
'Tag','C11Sub',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'C11QD';

h77 = uicontrol(...
'Parent',h66,...
'Units','characters',...
'Position',[22 2.53846153846154 10.4 1.07692307692308],...
'String','0',...
'Style','text',...
'Tag','C11QD',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'C11SC';

h78 = uicontrol(...
'Parent',h66,...
'Units','characters',...
'Position',[22 1 10.4 1.07692307692308],...
'String','0',...
'Style','text',...
'Tag','C11SC',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'C12Sub';

h79 = uicontrol(...
'Parent',h66,...
'Units','characters',...
'Position',[36.6 4.07692307692308 10.4 1.07692307692308],...
'String','0',...
'Style','text',...
'Tag','C12Sub',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'C12QD';

h80 = uicontrol(...
'Parent',h66,...
'Units','characters',...
'Position',[36.6 2.53846153846154 10.4 1.07692307692308],...
'String','0',...
'Style','text',...
'Tag','C12QD',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'C12SC';

h81 = uicontrol(...
'Parent',h66,...
'Units','characters',...
'Position',[36.6 1 10.4 1.07692307692308],...
'String','0',...
'Style','text',...
'Tag','C12SC',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text43';

h82 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'Position',[1.2 1.69230769230769 57.4 1.15384615384615],...
'String','Material Parameters: Vurgaftman, doi:10.1063/1.1368156',...
'Style','text',...
'Tag','text43',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text44';

h83 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'Position',[1.2 4.61538461538462 43.8 1.07692307692308],...
'String','CET: Ekins-Daukes, doi:10.1021/cg025502y',...
'Style','text',...
'Tag','text44',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text45';

h84 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'Position',[1.2 3.15384615384615 46.2 1.07692307692308],...
'String','mCET Cylinder: Bailey, doi:10.1063/1.3264967',...
'Style','text',...
'Tag','text45',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text46';

h85 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'Position',[61.2 2.61538461538462 40.4 1.07692307692308],...
'String','Created by: Steve Polly, RIT, 2014 v.2.0',...
'Style','text',...
'Tag','text46',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text47';

h86 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'Position',[73.2 1.46153846153846 16.4 1.07692307692308],...
'String','sjp5958@rit.edu',...
'Style','text',...
'Tag','text47',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text48';

h87 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'Position',[1.2 0.384615384615385 57.4 1.07692307692308],...
'String','Stiffness Calculator: Adachi, isbn: 9780470090329 pg. 49',...
'Style','text',...
'Tag','text48',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text80';

% h88 = uicontrol(...
% 'Parent',h1,...
% 'Units','characters',...
% 'Position',[62.6 0.384615384615385 37.8 1.07692307692308],...
% 'String','github.com/spolly/straincompensation',...
% 'Style','text',...
% 'Tag','text80',...
% 'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );


hsingleton = h1;


% --- Set application data first then calling the CreateFcn.
function local_CreateFcn(hObject, eventdata, createfcn, appdata)

if ~isempty(appdata)
   names = fieldnames(appdata);
   for i=1:length(names)
       name = char(names(i));
       setappdata(hObject, name, getfield(appdata,name));
   end
end

if ~isempty(createfcn)
   if isa(createfcn,'function_handle')
       createfcn(hObject, eventdata);
   else
       eval(createfcn);
   end
end


% --- Handles default GUIDE GUI creation and callback dispatch
function varargout = gui_mainfcn(gui_State, varargin)

gui_StateFields =  {'gui_Name'
    'gui_Singleton'
    'gui_OpeningFcn'
    'gui_OutputFcn'
    'gui_LayoutFcn'
    'gui_Callback'};
gui_Mfile = '';
for i=1:length(gui_StateFields)
    if ~isfield(gui_State, gui_StateFields{i})
        error(message('MATLAB:guide:StateFieldNotFound', gui_StateFields{ i }, gui_Mfile));
    elseif isequal(gui_StateFields{i}, 'gui_Name')
        gui_Mfile = [gui_State.(gui_StateFields{i}), '.m'];
    end
end

numargin = length(varargin);

if numargin == 0
    % SC_NEW_EXPORT
    % create the GUI only if we are not in the process of loading it
    % already
    gui_Create = true;
elseif local_isInvokeActiveXCallback(gui_State, varargin{:})
    % SC_NEW_EXPORT(ACTIVEX,...)
    vin{1} = gui_State.gui_Name;
    vin{2} = [get(varargin{1}.Peer, 'Tag'), '_', varargin{end}];
    vin{3} = varargin{1};
    vin{4} = varargin{end-1};
    vin{5} = guidata(varargin{1}.Peer);
    feval(vin{:});
    return;
elseif local_isInvokeHGCallback(gui_State, varargin{:})
    % SC_NEW_EXPORT('CALLBACK',hObject,eventData,handles,...)
    gui_Create = false;
else
    % SC_NEW_EXPORT(...)
    % create the GUI and hand varargin to the openingfcn
    gui_Create = true;
end

if ~gui_Create
    % In design time, we need to mark all components possibly created in
    % the coming callback evaluation as non-serializable. This way, they
    % will not be brought into GUIDE and not be saved in the figure file
    % when running/saving the GUI from GUIDE.
    designEval = false;
    if (numargin>1 && ishghandle(varargin{2}))
        fig = varargin{2};
        while ~isempty(fig) && ~ishghandle(fig,'figure')
            fig = get(fig,'parent');
        end

        designEval = isappdata(0,'CreatingGUIDEFigure') || isprop(fig,'__GUIDEFigure');
    end

    if designEval
        beforeChildren = findall(fig);
    end

    % evaluate the callback now
    varargin{1} = gui_State.gui_Callback;
    if nargout
        [varargout{1:nargout}] = feval(varargin{:});
    else
        feval(varargin{:});
    end

    % Set serializable of objects created in the above callback to off in
    % design time. Need to check whether figure handle is still valid in
    % case the figure is deleted during the callback dispatching.
    if designEval && ishghandle(fig)
        set(setdiff(findall(fig),beforeChildren), 'Serializable','off');
    end
else
    if gui_State.gui_Singleton
        gui_SingletonOpt = 'reuse';
    else
        gui_SingletonOpt = 'new';
    end

    % Check user passing 'visible' P/V pair first so that its value can be
    % used by oepnfig to prevent flickering
    gui_Visible = 'auto';
    gui_VisibleInput = '';
    for index=1:2:length(varargin)
        if length(varargin) == index || ~ischar(varargin{index})
            break;
        end

        % Recognize 'visible' P/V pair
        len1 = min(length('visible'),length(varargin{index}));
        len2 = min(length('off'),length(varargin{index+1}));
        if ischar(varargin{index+1}) && strncmpi(varargin{index},'visible',len1) && len2 > 1
            if strncmpi(varargin{index+1},'off',len2)
                gui_Visible = 'invisible';
                gui_VisibleInput = 'off';
            elseif strncmpi(varargin{index+1},'on',len2)
                gui_Visible = 'visible';
                gui_VisibleInput = 'on';
            end
        end
    end

    % Open fig file with stored settings.  Note: This executes all component
    % specific CreateFunctions with an empty HANDLES structure.


    % Do feval on layout code in m-file if it exists
    gui_Exported = ~isempty(gui_State.gui_LayoutFcn);
    % this application data is used to indicate the running mode of a GUIDE
    % GUI to distinguish it from the design mode of the GUI in GUIDE. it is
    % only used by actxproxy at this time.
    setappdata(0,genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name]),1);
    if gui_Exported
        gui_hFigure = feval(gui_State.gui_LayoutFcn, gui_SingletonOpt);

        % make figure invisible here so that the visibility of figure is
        % consistent in OpeningFcn in the exported GUI case
        if isempty(gui_VisibleInput)
            gui_VisibleInput = get(gui_hFigure,'Visible');
        end
        set(gui_hFigure,'Visible','off')

        % openfig (called by local_openfig below) does this for guis without
        % the LayoutFcn. Be sure to do it here so guis show up on screen.
        movegui(gui_hFigure,'onscreen');
    else
        gui_hFigure = local_openfig(gui_State.gui_Name, gui_SingletonOpt, gui_Visible);
        % If the figure has InGUIInitialization it was not completely created
        % on the last pass.  Delete this handle and try again.
        if isappdata(gui_hFigure, 'InGUIInitialization')
            delete(gui_hFigure);
            gui_hFigure = local_openfig(gui_State.gui_Name, gui_SingletonOpt, gui_Visible);
        end
    end
    if isappdata(0, genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name]))
        rmappdata(0,genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name]));
    end

    % Set flag to indicate starting GUI initialization
    setappdata(gui_hFigure,'InGUIInitialization',1);

    % Fetch GUIDE Application options
    gui_Options = getappdata(gui_hFigure,'GUIDEOptions');
    % Singleton setting in the GUI M-file takes priority if different
    gui_Options.singleton = gui_State.gui_Singleton;

    if ~isappdata(gui_hFigure,'GUIOnScreen')
        % Adjust background color
        if gui_Options.syscolorfig
            set(gui_hFigure,'Color', get(0,'DefaultUicontrolBackgroundColor'));
        end

        % Generate HANDLES structure and store with GUIDATA. If there is
        % user set GUI data already, keep that also.
        data = guidata(gui_hFigure);
        handles = guihandles(gui_hFigure);
        if ~isempty(handles)
            if isempty(data)
                data = handles;
            else
                names = fieldnames(handles);
                for k=1:length(names)
                    data.(char(names(k)))=handles.(char(names(k)));
                end
            end
        end
        guidata(gui_hFigure, data);
    end

    % Apply input P/V pairs other than 'visible'
    for index=1:2:length(varargin)
        if length(varargin) == index || ~ischar(varargin{index})
            break;
        end

        len1 = min(length('visible'),length(varargin{index}));
        if ~strncmpi(varargin{index},'visible',len1)
            try set(gui_hFigure, varargin{index}, varargin{index+1}), catch break, end
        end
    end

    % If handle visibility is set to 'callback', turn it on until finished
    % with OpeningFcn
    gui_HandleVisibility = get(gui_hFigure,'HandleVisibility');
    if strcmp(gui_HandleVisibility, 'callback')
        set(gui_hFigure,'HandleVisibility', 'on');
    end

    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure), varargin{:});

    if isscalar(gui_hFigure) && ishghandle(gui_hFigure)
        % Handle the default callbacks of predefined toolbar tools in this
        % GUI, if any
        guidemfile('restoreToolbarToolPredefinedCallback',gui_hFigure);

        % Update handle visibility
        set(gui_hFigure,'HandleVisibility', gui_HandleVisibility);

        % Call openfig again to pick up the saved visibility or apply the
        % one passed in from the P/V pairs
        if ~gui_Exported
            gui_hFigure = local_openfig(gui_State.gui_Name, 'reuse',gui_Visible);
        elseif ~isempty(gui_VisibleInput)
            set(gui_hFigure,'Visible',gui_VisibleInput);
        end
        if strcmpi(get(gui_hFigure, 'Visible'), 'on')
            figure(gui_hFigure);

            if gui_Options.singleton
                setappdata(gui_hFigure,'GUIOnScreen', 1);
            end
        end

        % Done with GUI initialization
        if isappdata(gui_hFigure,'InGUIInitialization')
            rmappdata(gui_hFigure,'InGUIInitialization');
        end

        % If handle visibility is set to 'callback', turn it on until
        % finished with OutputFcn
        gui_HandleVisibility = get(gui_hFigure,'HandleVisibility');
        if strcmp(gui_HandleVisibility, 'callback')
            set(gui_hFigure,'HandleVisibility', 'on');
        end
        gui_Handles = guidata(gui_hFigure);
    else
        gui_Handles = [];
    end

    if nargout
        [varargout{1:nargout}] = feval(gui_State.gui_OutputFcn, gui_hFigure, [], gui_Handles);
    else
        feval(gui_State.gui_OutputFcn, gui_hFigure, [], gui_Handles);
    end

    if isscalar(gui_hFigure) && ishghandle(gui_hFigure)
        set(gui_hFigure,'HandleVisibility', gui_HandleVisibility);
    end
end

function gui_hFigure = local_openfig(name, singleton, visible)

% openfig with three arguments was new from R13. Try to call that first, if
% failed, try the old openfig.
if nargin('openfig') == 2
    % OPENFIG did not accept 3rd input argument until R13,
    % toggle default figure visible to prevent the figure
    % from showing up too soon.
    gui_OldDefaultVisible = get(0,'defaultFigureVisible');
    set(0,'defaultFigureVisible','off');
    gui_hFigure = openfig(name, singleton);
    set(0,'defaultFigureVisible',gui_OldDefaultVisible);
else
    gui_hFigure = openfig(name, singleton, visible);
    %workaround for CreateFcn not called to create ActiveX
    if feature('HGUsingMATLABClasses')
        peers=findobj(findall(allchild(gui_hFigure)),'type','uicontrol','style','text');
        for i=1:length(peers)
            if isappdata(peers(i),'Control')
                actxproxy(peers(i));
            end
        end
    end
end

function result = local_isInvokeActiveXCallback(gui_State, varargin)

try
    result = ispc && iscom(varargin{1}) ...
             && isequal(varargin{1},gcbo);
catch
    result = false;
end

function result = local_isInvokeHGCallback(gui_State, varargin)

try
    fhandle = functions(gui_State.gui_Callback);
    result = ~isempty(findstr(gui_State.gui_Name,fhandle.file)) || ...
             (ischar(varargin{1}) ...
             && isequal(ishghandle(varargin{2}), 1) ...
             && (~isempty(strfind(varargin{1},[get(varargin{2}, 'Tag'), '_'])) || ...
                ~isempty(strfind(varargin{1}, '_CreateFcn'))) );
catch
    result = false;
end
